const XLSX = require('xlsx');
const path = 'C:\\Users\\makoto\\Documents\\アプリ開発\\VocabularyBase\\単語リスト\\出題頻度順リストのみ_英検英単語_updated.xlsx';
const wb = XLSX.readFile(path);

const extra = [
{rank:101,word:"vegetable",meaning:"野菜",example:"I eat a lot of vegetables every day.",translation:"私は毎日たくさんの野菜を食べます。"},
{rank:102,word:"grandmother",meaning:"祖母",example:"My grandmother lives in a small town.",translation:"私の祖母は小さな町に住んでいます。"},
{rank:103,word:"island",meaning:"島",example:"Hawaii is a beautiful island.",translation:"ハワイは美しい島です。"},
{rank:104,word:"hill",meaning:"丘",example:"We ran up the hill to see the sunset.",translation:"私たちは夕日を見るために丘を駆け上がりました。"},
{rank:105,word:"tooth",meaning:"歯",example:"Brush your teeth after meals.",translation:"食後は歯を磨きなさい。"},
{rank:106,word:"draw",meaning:"描く",example:"She can draw pictures very well.",translation:"彼女はとても上手に絵を描くことができます。"},
{rank:107,word:"success",meaning:"成功",example:"The school festival was a great success.",translation:"学校の文化祭は大成功でした。"},
{rank:108,word:"wind",meaning:"風",example:"A strong wind is blowing today.",translation:"今日は強い風が吹いています。"},
{rank:109,word:"stone",meaning:"石",example:"He threw a stone into the river.",translation:"彼は川に石を投げました。"},
{rank:110,word:"pork",meaning:"豚肉",example:"I like pork better than beef.",translation:"私は牛肉より豚肉の方が好きです。"},
{rank:111,word:"build",meaning:"建てる",example:"They are going to build a new house here.",translation:"彼らはここに新しい家を建てる予定です。"},
{rank:112,word:"pick",meaning:"選ぶ",example:"Please pick a color you like.",translation:"あなたの好きな色を選んでください。"},
{rank:113,word:"inside",meaning:"内側",example:"It is raining, so let's play inside.",translation:"雨が降っているので、内側で遊びましょう。"},
{rank:114,word:"factory",meaning:"工場",example:"My uncle works in a car factory.",translation:"私の叔父は車の工場で働いています。"},
{rank:115,word:"roof",meaning:"屋根",example:"The bird is on the roof of the house.",translation:"鳥が家の屋根の上にいます。"},
{rank:116,word:"past",meaning:"過去の",example:"I read a book about past events.",translation:"私は過去の出来事についての本を読みました。"},
{rank:117,word:"sailor",meaning:"船員",example:"He wants to be a sailor and travel the sea.",translation:"彼は船員になって海を旅したいと思っています。"},
{rank:118,word:"sugar",meaning:"砂糖",example:"How much sugar do you want in your tea?",translation:"紅茶にどれくらい砂糖が欲しいですか？"},
{rank:119,word:"shoulder",meaning:"肩",example:"He carries a heavy bag on his shoulder.",translation:"彼は重いかばんを肩に担いでいます。"},
{rank:120,word:"wood",meaning:"木材",example:"This desk is made of wood.",translation:"この机は木材でできています。"},
{rank:121,word:"seem",meaning:"～の様に見える",example:"You seem happy today.",translation:"あなたは今日幸せに見えます。"},
{rank:122,word:"textbook",meaning:"教科書",example:"Please open your English textbook.",translation:"英語の教科書を開いてください。"},
{rank:123,word:"wake",meaning:"目が覚める",example:"I usually wake up at six o'clock.",translation:"私は普通6時に目が覚めます。"},
{rank:124,word:"pay",meaning:"支払う",example:"I will pay for the lunch.",translation:"私が昼食代を支払います。"},
{rank:125,word:"salt",meaning:"塩",example:"Could you pass me the salt, please?",translation:"私に塩を取ってくれませんか？"},
{rank:126,word:"farmer",meaning:"農家",example:"The farmer grows many delicious vegetables.",translation:"その農家はたくさんのおいしい野菜を育てています。"},
{rank:127,word:"cloud",meaning:"雲",example:"There are white clouds in the sky.",translation:"空に白い雲があります。"},
{rank:128,word:"thousand",meaning:"千",example:"This dictionary costs about two thousand yen.",translation:"この辞書は約2千円かかります。"},
{rank:129,word:"ask",meaning:"たずねる",example:"May I ask you a question?",translation:"あなたに質問をたずねてもいいですか？"},
{rank:130,word:"land",meaning:"土地",example:"My grandfather has a large land.",translation:"私の祖父は大きな土地を持っています。"},
{rank:131,word:"planet",meaning:"惑星",example:"The Earth is a beautiful planet.",translation:"地球は美しい惑星です。"},
{rank:132,word:"pond",meaning:"池",example:"There are some frogs in the pond.",translation:"池の中にカエルが何匹かいます。"},
{rank:133,word:"nature",meaning:"自然",example:"I love the beautiful nature of this town.",translation:"私はこの町の美しい自然が大好きです。"},
{rank:134,word:"pig",meaning:"ブタ",example:"The little pig is very cute.",translation:"その小さなブタはとてもかわいいです。"},
{rank:135,word:"rabbit",meaning:"ウサギ",example:"She keeps a white rabbit as a pet.",translation:"彼女は白いウサギをペットとして飼っています。"},
{rank:136,word:"laugh",meaning:"笑う",example:"He always makes me laugh.",translation:"彼はいつも私を笑わせます。"},
{rank:137,word:"just",meaning:"ちょうど",example:"The train just arrived at the station.",translation:"電車がちょうど駅に到着しました。"},
{rank:138,word:"real",meaning:"ほんとうの",example:"Is this story real?",translation:"この話はほんとうですか？"},
{rank:139,word:"stood",meaning:"立った",example:"He stood by the window and looked outside.",translation:"彼は窓のそばに立って外を見ました。"},
{rank:140,word:"while",meaning:"～する間",example:"Please wait here while I make a phone call.",translation:"私が電話をかける間、ここで待っていてください。"},
{rank:141,word:"fail",meaning:"失敗する",example:"If you don't study, you will fail the test.",translation:"勉強しないと、テストに失敗するでしょう。"},
{rank:142,word:"put",meaning:"置く",example:"Please put your bag on the desk.",translation:"あなたのかばんを机の上に置いてください。"},
{rank:143,word:"arm",meaning:"腕",example:"He has long arms.",translation:"彼は長い腕を持っています。"},
{rank:144,word:"listen",meaning:"聴く",example:"I like to listen to music.",translation:"私は音楽を聴くのが好きです。"},
{rank:145,word:"enjoyed",meaning:"楽しんだ",example:"We enjoyed playing soccer yesterday.",translation:"私たちは昨日サッカーをして楽しみました。"},
{rank:146,word:"spoke",meaning:"話した",example:"He spoke to me in English.",translation:"彼は私に英語で話しました。"},
{rank:147,word:"save",meaning:"節約する",example:"I want to save money to buy a new bike.",translation:"私は新しい自転車を買うためにお金を節約したいです。"},
{rank:148,word:"tried",meaning:"試した",example:"I tried to read the English book.",translation:"私はその英語の本を読もうと試しました。"},
{rank:149,word:"still",meaning:"まだ",example:"It is still raining outside.",translation:"外はまだ雨が降っています。"},
{rank:150,word:"sold",meaning:"売った",example:"He sold his old car last week.",translation:"彼は先週、古い車を売りました。"},
{rank:151,word:"foolish",meaning:"愚かな",example:"It is a foolish idea to go out in the storm.",translation:"嵐の中を外出するのは愚かな考えです。"},
{rank:152,word:"watched",meaning:"見た",example:"I watched TV after dinner.",translation:"私は夕食のあとにテレビを見ました。"},
{rank:153,word:"first",meaning:"1番目",example:"He was the first student to arrive.",translation:"彼は到着した1番目の生徒でした。"},
{rank:154,word:"they",meaning:"彼らは",example:"They are my friends.",translation:"彼らは私の友達です。"},
{rank:155,word:"played",meaning:"演奏した",example:"She played the piano beautifully.",translation:"彼女はピアノを美しく演奏しました。"},
{rank:156,word:"realize",meaning:"実現する",example:"He worked hard to realize his dream.",translation:"彼は夢を実現するために一生懸命働きました。"},
{rank:157,word:"important",meaning:"重要な",example:"Water is very important for all living things.",translation:"水はすべての生き物にとってとても重要です。"},
{rank:158,word:"forth",meaning:"4番目",example:"My seat is the fourth one from the front.",translation:"私の席は前から4番目のものです。"},
{rank:159,word:"hers",meaning:"彼女のもの",example:"This pen is mine, and that one is hers.",translation:"このペンは私のもので、あちらは彼女のものです。"},
{rank:160,word:"honest",meaning:"正直な",example:"He is an honest boy.",translation:"彼は正直な男の子です。"},
{rank:161,word:"between",meaning:"～と～の間",example:"There is a river between the two towns.",translation:"その2つの町の間に川があります。"},
{rank:162,word:"took",meaning:"取った",example:"He took a book from his bag.",translation:"彼はかばんから本を取りました。"},
{rank:163,word:"zoo",meaning:"動物園",example:"We went to the zoo to see the pandas.",translation:"私たちはパンダを見るために動物園に行きました。"},
{rank:164,word:"quiet",meaning:"静かな",example:"Please keep quiet in the hospital.",translation:"病院では静かにしていてください。"},
{rank:165,word:"then",meaning:"そのとき",example:"I was studying English then.",translation:"私はそのとき英語を勉強していました。"},
{rank:166,word:"when",meaning:"～するとき",example:"I was sleeping when he called me.",translation:"彼が電話してきたとき、私は眠っていました。"},
{rank:167,word:"got",meaning:"得た",example:"I got a nice present from my aunt.",translation:"私は叔母から素敵なプレゼントをもらいました。"},
{rank:168,word:"yours",meaning:"あなたのもの",example:"Is this notebook yours?",translation:"このノートはあなたのものですか？"},
{rank:169,word:"joy",meaning:"喜び",example:"Tears of joy ran down her face.",translation:"喜びの涙が彼女の顔を流れ落ちました。"},
{rank:170,word:"weak",meaning:"弱い",example:"I was sick and my body was weak.",translation:"私は病気で体が弱っていました。"},
{rank:171,word:"it",meaning:"それは",example:"I have a dog. It is very cute.",translation:"私は犬を飼っています。それはとてもかわいいです。"},
{rank:172,word:"thought",meaning:"考え",example:"That is a very good thought.",translation:"それはとても良い考えです。"},
{rank:173,word:"use",meaning:"使う",example:"May I use your dictionary?",translation:"あなたの辞書を使ってもいいですか？"},
{rank:174,word:"senior",meaning:"年上の",example:"He is a senior high school student.",translation:"彼は高校の生徒です。"},
{rank:175,word:"waste",meaning:"浪費",example:"Playing video games all day is a waste of time.",translation:"一日中ビデオゲームをするのは時間の浪費です。"},
{rank:176,word:"net",meaning:"網",example:"He caught the butterfly with a net.",translation:"彼は網でその蝶を捕まえました。"},
{rank:177,word:"had",meaning:"食べた",example:"I had bread and milk for breakfast.",translation:"私は朝食にパンと牛乳を食べました。"},
{rank:178,word:"lose",meaning:"失う",example:"Don't lose your ticket.",translation:"チケットをなくさないでください。"},
{rank:179,word:"bought",meaning:"持ってきた",example:"He bought his favorite CD to the party.",translation:"彼はパーティーにお気に入りのCDを持ってきました。"},
{rank:180,word:"poor",meaning:"貧乏な",example:"He helped a poor man on the street.",translation:"彼は通りで貧乏な男を助けました。"},
{rank:181,word:"rainy",meaning:"雨降りの",example:"We can't play baseball on a rainy day.",translation:"雨降りの日には野球をすることができません。"},
{rank:182,word:"her",meaning:"彼女の",example:"I know her name.",translation:"私は彼女の名前を知っています。"},
{rank:183,word:"its",meaning:"その",example:"The dog is wagging its tail.",translation:"犬がそのしっぽを振っています。"},
{rank:184,word:"weather",meaning:"天気",example:"The weather is very nice today.",translation:"今日は天気がとても良いです。"},
{rank:185,word:"wave",meaning:"波",example:"The waves are high today.",translation:"今日は波が高いです。"},
{rank:186,word:"went",meaning:"行った",example:"I went to the library yesterday.",translation:"私は昨日図書館に行きました。"},
{rank:187,word:"but",meaning:"しかし",example:"I am tired, but I have to do my homework.",translation:"私は疲れていますが、しかし宿題をしなければなりません。"},
{rank:188,word:"her",meaning:"彼女の",example:"Her bag is red.",translation:"彼女のかばんは赤いです。"},
{rank:189,word:"once",meaning:"かつて",example:"There was once a big castle here.",translation:"ここにはかつて大きな城がありました。"},
{rank:190,word:"his",meaning:"彼の",example:"This is his bicycle.",translation:"これは彼の自転車です。"},
{rank:191,word:"stay",meaning:"滞在",example:"I will stay at my uncle's house.",translation:"私は叔父の家に滞在します。"},
{rank:192,word:"you",meaning:"あなたは",example:"Are you a student?",translation:"あなたは生徒ですか？"},
{rank:193,word:"their",meaning:"彼らの",example:"Their car is very fast.",translation:"彼らの車はとても速いです。"},
{rank:194,word:"your",meaning:"あなたの",example:"What is your name?",translation:"あなたの名前は何ですか？"},
{rank:195,word:"yesterday",meaning:"昨日",example:"It rained yesterday.",translation:"昨日は雨が降りました。"},
{rank:196,word:"east",meaning:"東",example:"The sun rises in the east.",translation:"太陽は東から昇ります。"},
{rank:197,word:"she",meaning:"彼女は",example:"She is my best friend.",translation:"彼女は私の親友です。"},
{rank:198,word:"How",meaning:"どのぐらい",example:"How much is this book?",translation:"この本はどのぐらいですか？"},
{rank:199,word:"please",meaning:"喜ばせる",example:"He bought flowers to please his mother.",translation:"彼は母親を喜ばせるために花を買いました。"},
{rank:200,word:"toy",meaning:"玩具",example:"My little brother has many toys.",translation:"私の小さな弟はたくさんの玩具を持っています。"},
{rank:201,word:"used",meaning:"使った",example:"I used my computer to do my homework.",translation:"私は宿題をするためにコンピューターを使った。"},
{rank:202,word:"fat",meaning:"太った",example:"My cat is a little fat.",translation:"私の猫は少し太っている。"},
{rank:203,word:"dislike",meaning:"嫌う",example:"I dislike eating carrots.",translation:"私はニンジンを食べるのが嫌いだ。"},
{rank:204,word:"it",meaning:"それは",example:"Look at the bird. It is very small.",translation:"あの鳥を見て。それはとても小さいです。"},
{rank:205,word:"he",meaning:"彼は",example:"He is my English teacher.",translation:"彼は私の英語の先生です。"},
{rank:206,word:"studied",meaning:"勉強した",example:"I studied math for two hours yesterday.",translation:"私は昨日2時間数学を勉強した。"},
{rank:207,word:"cloudy",meaning:"曇った",example:"It is cloudy today.",translation:"今日は曇っている。"},
{rank:208,word:"worried",meaning:"心配した",example:"My mother was worried about me.",translation:"母は私のことを心配していた。"},
{rank:209,word:"made",meaning:"作った",example:"She made a delicious cake.",translation:"彼女は美味しいケーキを作った。"},
{rank:210,word:"guess",meaning:"推測する",example:"Can you guess what is in this box?",translation:"この箱の中に何が入っているか推測できますか？"},
{rank:211,word:"event",meaning:"出来事",example:"The school festival is a big event.",translation:"文化祭は大きな出来事です。"},
{rank:212,word:"sweet",meaning:"甘い",example:"This apple is very sweet.",translation:"このリンゴはとても甘いです。"},
{rank:213,word:"fruit",meaning:"果物",example:"I eat fruit every morning.",translation:"私は毎朝果物を食べます。"},
{rank:214,word:"fourteen",meaning:"14",example:"She is fourteen years old.",translation:"彼女は14歳です。"},
{rank:215,word:"soup",meaning:"スープ",example:"I had hot soup for lunch.",translation:"私は昼食に温かいスープを飲んだ。"},
{rank:216,word:"science",meaning:"科学",example:"Science is my favorite subject.",translation:"科学は私のお気に入りの科目です。"},
{rank:217,word:"drink",meaning:"飲む",example:"I drink milk every day.",translation:"私は毎日牛乳を飲みます。"},
{rank:218,word:"station",meaning:"駅",example:"I will meet you at the station.",translation:"駅であなたに会います。"},
{rank:219,word:"seventy",meaning:"70",example:"My grandfather is seventy years old.",translation:"私の祖父は70歳です。"},
{rank:220,word:"cake",meaning:"ケーキ",example:"Let's make a birthday cake.",translation:"誕生日ケーキを作りましょう。"},
{rank:221,word:"stand",meaning:"立つ",example:"Please stand up.",translation:"立ってください。"},
{rank:222,word:"hope",meaning:"望む",example:"I hope you have a good time.",translation:"あなたが良い時間を過ごせるよう望みます。"},
{rank:223,word:"street",meaning:"通り",example:"There are many cars on the street.",translation:"その通りにはたくさんの車があります。"},
{rank:224,word:"friend",meaning:"友達",example:"He is my best friend.",translation:"彼は私の親友です。"},
{rank:225,word:"rise",meaning:"昇る",example:"The sun will rise early tomorrow.",translation:"明日は太陽が早く昇るでしょう。"},
{rank:226,word:"sometimes",meaning:"時々",example:"I sometimes play tennis on Sundays.",translation:"私は日曜日には時々テニスをします。"},
{rank:227,word:"frog",meaning:"カエル",example:"I saw a green frog near the river.",translation:"川の近くで緑色のカエルを見た。"},
{rank:228,word:"supermarket",meaning:"スーパー",example:"My mother went to the supermarket.",translation:"母はスーパーに行きました。"},
{rank:229,word:"small",meaning:"小さい",example:"She has a small bag.",translation:"彼女は小さいかばんを持っています。"},
{rank:230,word:"summer",meaning:"夏",example:"I like swimming in the summer.",translation:"私は夏に泳ぐのが好きです。"},
{rank:231,word:"stop",meaning:"止める",example:"Please stop talking.",translation:"話すのを止めてください。"},
{rank:232,word:"subject",meaning:"科目",example:"What is your favorite subject?",translation:"あなたのお気に入りの科目は何ですか？"},
{rank:233,word:"help",meaning:"助ける",example:"Can you help me with my homework?",translation:"私の宿題を手伝ってくれませんか？"},
{rank:234,word:"green",meaning:"緑",example:"Look at those green trees.",translation:"あの緑の木々を見てください。"},
{rank:235,word:"here",meaning:"ここに",example:"Please put the box here.",translation:"その箱をここに置いてください。"},
{rank:236,word:"garbage",meaning:"ゴミ",example:"Please throw the garbage in the trash can.",translation:"ゴミはゴミ箱に捨ててください。"},
{rank:237,word:"by",meaning:"のそばに",example:"He was standing by the door.",translation:"彼はドアのそばに立っていました。"},
{rank:238,word:"sister",meaning:"姉妹",example:"I have an older sister.",translation:"私には姉がいます。"},
{rank:239,word:"good",meaning:"良い",example:"This is a very good book.",translation:"これはとても良い本です。"},
{rank:240,word:"seven",meaning:"7",example:"There are seven days in a week.",translation:"1週間には7つの日があります。"},
{rank:241,word:"family",meaning:"家族",example:"My family is very important to me.",translation:"私の家族は私にとってとても重要です。"},
{rank:242,word:"food",meaning:"食べ物",example:"We need to buy some food.",translation:"私たちはいくらかの食べ物を買う必要があります。"},
{rank:243,word:"hot",meaning:"暑い",example:"It is very hot today.",translation:"今日はとても暑いです。"},
{rank:244,word:"great",meaning:"すばらしい",example:"That is a great idea!",translation:"それはすばらしいアイデアですね！"},
{rank:245,word:"hear",meaning:"聞く",example:"I can hear the birds singing.",translation:"鳥が歌っているのを聞くことができます。"},
{rank:246,word:"funny",meaning:"おかしな",example:"He told us a funny story.",translation:"彼は私たちにおかしな話をしました。"},
{rank:247,word:"festival",meaning:"祭り",example:"We went to the summer festival.",translation:"私たちは夏祭りに行きました。"},
{rank:248,word:"straight",meaning:"まっすぐに",example:"Go straight along this street.",translation:"この通りをまっすぐに進んでください。"},
{rank:249,word:"telephone",meaning:"電話",example:"Please answer the telephone.",translation:"電話に出てください。"},
{rank:250,word:"forty",meaning:"40",example:"My father is forty years old.",translation:"私の父は40歳です。"},
{rank:251,word:"sport",meaning:"スポーツ",example:"Baseball is a popular sport in Japan.",translation:"野球は日本で人気のスポーツです。"},
{rank:252,word:"Do",meaning:"する",example:"Do you like music?",translation:"あなたは音楽が好きですか？"},
{rank:253,word:"go",meaning:"行く",example:"Let's go to the park.",translation:"公園に行きましょう。"},
{rank:254,word:"strong",meaning:"強い",example:"He is very strong.",translation:"彼はとても強いです。"},
{rank:255,word:"teacher",meaning:"先生",example:"Mr. Smith is a math teacher.",translation:"スミス先生は数学の先生です。"},
{rank:256,word:"head",meaning:"頭",example:"I have a pain in my head.",translation:"私は頭に痛みがあります。"},
{rank:257,word:"eighteen",meaning:"18",example:"He is eighteen years old.",translation:"彼は18歳です。"},
{rank:258,word:"culture",meaning:"文化",example:"I want to learn about Japanese culture.",translation:"私は日本の文化について学びたいです。"},
{rank:259,word:"second",meaning:"2番目",example:"This is my second visit to Kyoto.",translation:"これが私の2回目の京都訪問です。"},
{rank:260,word:"homework",meaning:"宿題",example:"Did you finish your homework?",translation:"あなたは宿題を終えましたか？"},
{rank:261,word:"language",meaning:"言語",example:"English is a very useful language.",translation:"英語はとても役に立つ言語です。"},
{rank:262,word:"swim",meaning:"泳ぐ",example:"Can you swim fast?",translation:"あなたは速く泳ぐことができますか？"},
{rank:263,word:"fast",meaning:"速い",example:"This car is very fast.",translation:"この車はとても速いです。"},
{rank:264,word:"six",meaning:"6",example:"I have six pencils.",translation:"私は6本の鉛筆を持っています。"},
{rank:265,word:"school",meaning:"学校",example:"I go to school by bus.",translation:"私はバスで学校に行きます。"},
{rank:266,word:"speak",meaning:"話す",example:"Can you speak English?",translation:"あなたは英語を話すことができますか？"},
{rank:267,word:"ship",meaning:"船",example:"Look at that big ship on the sea.",translation:"海の上のあの大きな船を見てください。"},
{rank:268,word:"ten",meaning:"10",example:"I bought ten apples.",translation:"私は10個のリンゴを買いました。"},
{rank:269,word:"shopping",meaning:"買物",example:"I went shopping with my mother.",translation:"私は母と買物に行きました。"},
{rank:270,word:"hospital",meaning:"病院",example:"My uncle works in a hospital.",translation:"私の叔父は病院で働いています。"},
{rank:271,word:"sing",meaning:"歌う",example:"She likes to sing songs.",translation:"彼女は歌を歌うのが好きです。"},
{rank:272,word:"famous",meaning:"有名な",example:"He is a famous soccer player.",translation:"彼は有名なサッカー選手です。"},
{rank:273,word:"fifty",meaning:"50",example:"There are fifty states in the USA.",translation:"アメリカには50の州があります。"},
{rank:274,word:"shop",meaning:"店",example:"Let's go to the flower shop.",translation:"花屋に行きましょう。"},
{rank:275,word:"season",meaning:"季節",example:"Which season do you like best?",translation:"どの季節が一番好きですか？"},
{rank:276,word:"delicious",meaning:"おいしい",example:"This pizza is very delicious.",translation:"このピザはとてもおいしいです。"},
{rank:277,word:"short",meaning:"短い",example:"She has short hair.",translation:"彼女は短い髪をしています。"},
{rank:278,word:"everyone",meaning:"みんな",example:"Everyone likes him.",translation:"みんな彼が好きです。"},
{rank:279,word:"star",meaning:"星",example:"I can see many stars tonight.",translation:"今夜はたくさんの星を見ることができます。"},
{rank:280,word:"soft",meaning:"柔らかい",example:"This bed is very soft.",translation:"このベッドはとても柔らかいです。"},
{rank:281,word:"from",meaning:"～から",example:"Where are you from?",translation:"あなたはどこから来ましたか？"},
{rank:282,word:"happy",meaning:"幸福な",example:"I am very happy today.",translation:"私は今日とても幸せです。"},
{rank:283,word:"buy",meaning:"買う",example:"I want to buy a new bag.",translation:"私は新しいかばんを買いたいです。"},
{rank:284,word:"Friday",meaning:"金曜日",example:"We have an English class on Friday.",translation:"私たちは金曜日に英語の授業があります。"},
{rank:285,word:"have",meaning:"持っている",example:"I have two dogs.",translation:"私は2匹の犬を飼っています。"},
{rank:286,word:"scientist",meaning:"科学者",example:"He wants to be a scientist in the future.",translation:"彼は将来、科学者になりたいと思っています。"},
{rank:287,word:"girl",meaning:"少女",example:"The girl in the red dress is my sister.",translation:"赤いドレスを着た少女は私の妹です。"},
{rank:288,word:"theirs",meaning:"彼らのもの",example:"That house is theirs.",translation:"あの家は彼らのものです。"},
{rank:289,word:"favorite",meaning:"お気に入りの",example:"What is your favorite food?",translation:"あなたのお気に入りの食べ物は何ですか？"},
{rank:290,word:"spell",meaning:"をつづる",example:"How do you spell your name?",translation:"あなたの名前はどうつづりますか？"},
{rank:291,word:"September",meaning:"９月",example:"My birthday is in September.",translation:"私の誕生日は9月です。"},
{rank:292,word:"Sunday",meaning:"日曜日",example:"I play soccer every Sunday.",translation:"私は毎週日曜日にサッカーをします。"},
{rank:293,word:"beautiful",meaning:"美しい",example:"She gave me a beautiful flower.",translation:"彼女は私に美しい花をくれました。"},
{rank:294,word:"table",meaning:"つくえ",example:"The book is on the table.",translation:"本はテーブルの上にあります。"},
{rank:295,word:"fifteen",meaning:"15",example:"The bus will arrive in fifteen minutes.",translation:"バスは15分で到着します。"},
{rank:296,word:"desk",meaning:"机",example:"I study at my desk.",translation:"私は自分の机で勉強します。"},
{rank:297,word:"grape",meaning:"ブドウ",example:"I like eating grapes.",translation:"私はブドウを食べるのが好きです。"},
{rank:298,word:"for",meaning:"のために",example:"I bought this present for you.",translation:"私はあなたのためにこのプレゼントを買いました。"},
{rank:299,word:"four",meaning:"4",example:"A dog has four legs.",translation:"犬には4本の脚があります。"},
{rank:300,word:"fun",meaning:"楽しみ",example:"Playing tennis is a lot of fun.",translation:"テニスをするのはとても楽しいです。"},
];

// Read existing 4級 data
const existing = XLSX.utils.sheet_to_json(wb.Sheets['4級']);
const allRows = [...existing, ...extra.map(d => ({'列1':d.rank,'列2':d.word,'列3':d.meaning,'例文':d.example,'例文訳':d.translation}))];
const ws = XLSX.utils.json_to_sheet(allRows);
ws['!cols'] = [{wch:5},{wch:15},{wch:20},{wch:50},{wch:50}];
wb.Sheets['4級'] = ws;
XLSX.writeFile(wb, path);
console.log('4級 updated: ' + allRows.length + ' words total');
