const xlsx = require('xlsx');
const fs = require('fs');

const filePath = String.raw`C:\Users\makoto\Documents\GitHub\VocabularyBase\単語リスト\出題頻度順リストのみ_英検英単語.xlsx`;
const outPath = filePath.replace('.xlsx', '_updated.xlsx');
const targetFile = fs.existsSync(outPath) ? outPath : filePath;

const generatedData = [
  {"idx": 31, "en": "He completely recovered from his foot injury.", "ja": "彼は足の怪我から完全に回復した。"},
  {"idx": 32, "en": "The room fell into a deep silence.", "ja": "部屋は深い沈黙に包まれた。"},
  {"idx": 33, "en": "These shoes are too tight for me.", "ja": "これらの靴は私にはきつすぎる。"},
  {"idx": 34, "en": "We must protect the natural environment.", "ja": "私たちは自然環境を保護しなければならない。"},
  {"idx": 35, "en": "Be careful when you use a sharp knife.", "ja": "鋭いナイフを使う時は気をつけて。"},
  {"idx": 36, "en": "Look behind the door.", "ja": "ドアの背後を見て。"},
  {"idx": 37, "en": "I'm sorry to bother you when you are busy.", "ja": "あなたが忙しい時に迷惑をかけてすみません。"},
  {"idx": 38, "en": "Please call this number in an emergency.", "ja": "緊急の時はこの番号に電話してください。"},
  {"idx": 39, "en": "Don't waste your precious time on video games.", "ja": "テレビゲームで貴重な時間を浪費してはいけない。"},
  {"idx": 40, "en": "He spends a large amount of money on books.", "ja": "彼は本に多額のお金を費やす。"},
  {"idx": 41, "en": "Being tall is an advantage in basketball.", "ja": "背が高いことはバスケットボールにおいて有利だ。"},
  {"idx": 42, "en": "I saw a strange object flying in the sky.", "ja": "空を飛ぶ奇妙な物体を見た。"},
  {"idx": 43, "en": "If you add 2 and 3, you get 5.", "ja": "2と3を足し算すると5になる。"},
  {"idx": 44, "en": "The fish swam up to the surface of the water.", "ja": "魚は水面まで泳いで上がってきた。"},
  {"idx": 45, "en": "The earthquake destroyed many old buildings.", "ja": "地震が多くの古い建物を破壊した。"},
  {"idx": 46, "en": "He has a lot of knowledge about ancient history.", "ja": "彼は古代史について多くの知識を持っている。"},
  {"idx": 47, "en": "She will continue to study English in college.", "ja": "彼女は大学でも英語を勉強し続けるだろう。"},
  {"idx": 48, "en": "He replied to my email immediately.", "ja": "彼は私のメールに即座に返信した。"},
  {"idx": 49, "en": "Please correct any mistakes in this report.", "ja": "このレポートの間違いを訂正してください。"},
  {"idx": 50, "en": "The government announced a new economic plan.", "ja": "政府が新しい経済計画を発表した。"},
  {"idx": 51, "en": "Please raise your hand if you have a question.", "ja": "質問がある場合は手を挙げてください。"},
  {"idx": 52, "en": "I didn't mean to hurt your feelings.", "ja": "あなたの感情を傷つけるつもりはありませんでした。"},
  {"idx": 53, "en": "The scientists did a new experiment in the lab.", "ja": "科学者たちは実験室で新しい実験を行った。"},
  {"idx": 54, "en": "I don't want to fail the math test.", "ja": "私は数学のテストに失敗したくない。"},
  {"idx": 55, "en": "Wood is a good material for building houses.", "ja": "木は家を建てるための良い材料だ。"},
  {"idx": 56, "en": "Have you seen any good movies recently?", "ja": "最近何か面白い映画を見ましたか？"},
  {"idx": 57, "en": "The news spread quickly around the school.", "ja": "そのニュースは学校中に素早く広がった。"},
  {"idx": 58, "en": "The traffic is very heavy this morning.", "ja": "今朝は交通がとても激しい。"},
  {"idx": 59, "en": "He prefers modern art to classical art.", "ja": "彼は古典芸術より現代美術を好む。"},
  {"idx": 60, "en": "We should try to reduce plastic waste.", "ja": "プラスチック廃棄物を減らすように努めるべきだ。"},
  {"idx": 61, "en": "He lives at a distance of 5 miles from here.", "ja": "彼はここから5マイルの距離に住んでいる。"},
  {"idx": 62, "en": "This is a great opportunity to learn something new.", "ja": "これは何か新しいことを学ぶ素晴らしい好機だ。"},
  {"idx": 63, "en": "Fishing is an outdoor activity.", "ja": "釣りは屋外の活動だ。"},
  {"idx": 64, "en": "She wants to study abroad in the future.", "ja": "彼女は将来外国で勉強したいと考えている。"},
  {"idx": 65, "en": "I prefer tea to coffee.", "ja": "私はコーヒーよりお茶を好む。"},
  {"idx": 66, "en": "He didn't mention anything about his plan.", "ja": "彼は計画について何も言及しなかった。"},
  {"idx": 67, "en": "Although it was raining, they went shopping.", "ja": "雨が降っていたけれども、彼らは買い物に出かけた。"},
  {"idx": 68, "en": "Hawaii has a warm climate all year round.", "ja": "ハワイは一年中温暖な気候だ。"},
  {"idx": 69, "en": "The car is old but in good condition.", "ja": "その車は古いが、良い状態だ。"},
  {"idx": 70, "en": "His performance made a strong impression on me.", "ja": "彼の演技は私に強い印象を与えた。"},
  {"idx": 71, "en": "She bought several items at the supermarket.", "ja": "彼女はスーパーでいくつかの品物を買った。"},
  {"idx": 72, "en": "The company made a huge profit this year.", "ja": "その会社は今年莫大な利益を上げた。"},
  {"idx": 73, "en": "They conducted a survey on online learning.", "ja": "彼らはオンライン学習に関する調査を実施した。"},
  {"idx": 74, "en": "The sun is beginning to sink in the west.", "ja": "太陽が西に沈み始めている。"},
  {"idx": 75, "en": "She missed school because of illness.", "ja": "彼女は病気が原因で学校を休んだ。"},
  {"idx": 76, "en": "This ice cream has a sweet lemon flavor.", "ja": "このアイスクリームは甘いレモンの風味がある。"},
  {"idx": 77, "en": "He is an expert in Japanese history.", "ja": "彼は日本史の専門家だ。"},
  {"idx": 78, "en": "Can I borrow your pen for a moment?", "ja": "少しの間ペンを借りてもいいですか？"},
  {"idx": 79, "en": "Did you notice any change in his behavior?", "ja": "彼の振る舞いの変化に気づきましたか？"},
  {"idx": 80, "en": "He decided to quit his job.", "ja": "彼は仕事を辞めることを決心した。"},
  {"idx": 81, "en": "Don't ask such a silly question.", "ja": "そんな馬鹿な質問をしないで。"},
  {"idx": 82, "en": "He was born into a wealthy family.", "ja": "彼は裕福な家庭に生まれた。"},
  {"idx": 83, "en": "You should behave politely in public.", "ja": "公共の場では礼儀正しく振る舞うべきだ。"},
  {"idx": 84, "en": "The number of young people continues to decrease.", "ja": "若者の数は減少し続けている。"},
  {"idx": 85, "en": "Please divide the cake into equal pieces.", "ja": "ケーキを均等な部分に分割してください。"},
  {"idx": 86, "en": "He tried to ignore the loud noise.", "ja": "彼は大きな騒音を無視しようとした。"},
  {"idx": 87, "en": "You shouldn't judge people by their appearance.", "ja": "外見で人を判断するべきではない。"},
  {"idx": 88, "en": "She helped to organize the school festival.", "ja": "彼女は文化祭を組織するのを手伝った。"},
  {"idx": 89, "en": "He wants to overcome his fear of heights.", "ja": "彼は高所恐怖症を克服したいと考えている。"},
  {"idx": 90, "en": "The road was too narrow for a bus to pass.", "ja": "その道はバスが通るには幅が狭すぎた。"},
  {"idx": 121, "en": "She can speak English and French as well.", "ja": "彼女は英語を話し、その上フランス語も話せる。"},
  {"idx": 122, "en": "He is very good at playing the piano.", "ja": "彼はピアノを弾くのがとても上手だ。"},
  {"idx": 123, "en": "You are responsible for the team's success.", "ja": "あなたはチームの成功に対して責任がある。"},
  {"idx": 124, "en": "We had to call off the picnic due to rain.", "ja": "雨のためピクニックを中止しなければならなかった。"},
  {"idx": 125, "en": "Bring an umbrella in case it rains.", "ja": "雨が降った場合に備えて傘を持っていきなさい。"},
  {"idx": 126, "en": "On average, he sleeps 8 hours a night.", "ja": "平均して、彼は一晩に8時間眠る。"},
  {"idx": 127, "en": "I decided to go to the station on foot.", "ja": "私は歩いて駅に行くことにした。"},
  {"idx": 128, "en": "The elevator is completely out of order.", "ja": "エレベーターが完全に故障している。"},
  {"idx": 129, "en": "He broke the window on purpose.", "ja": "彼はわざと窓を割った。"},
  {"idx": 130, "en": "Stay away from the hot stove.", "ja": "熱いストーブから離れていなさい。"},
  {"idx": 131, "en": "Many people suffer from allergies in spring.", "ja": "春には多くの人がアレルギーに悩まされる。"},
  {"idx": 132, "en": "You must apologize to him for your mistake.", "ja": "あなたは彼に間違いを謝らなければならない。"},
  {"idx": 133, "en": "She succeeded in getting a good job.", "ja": "彼女は良い仕事を得ることに成功した。"},
  {"idx": 134, "en": "It turned out to be a good day after all.", "ja": "結局、良い一日になった。"},
  {"idx": 135, "en": "That singer is very popular with teenagers.", "ja": "その歌手は10代に非常に人気がある。"},
  {"idx": 136, "en": "I am entirely sick of his endless complaints.", "ja": "彼の終わりのない不満にはうんざりしている。"},
  {"idx": 137, "en": "It is unlikely to rain tomorrow.", "ja": "明日は雨が降りそうにない。"},
  {"idx": 138, "en": "I have to study hard to catch up with my class.", "ja": "クラスに追いつくために一生懸命勉強しなければならない。"},
  {"idx": 139, "en": "His opinion differs from mine.", "ja": "彼の意見は私のとは違う。"},
  {"idx": 140, "en": "Please buy the tickets in advance.", "ja": "前もってチケットを買っておいてください。"},
  {"idx": 141, "en": "She left the house in a hurry.", "ja": "彼女は急いで家を出た。"},
  {"idx": 142, "en": "Would you like to participate in the contest?", "ja": "コンテストに参加したいですか？"},
  {"idx": 143, "en": "Sooner or later, you will understand my feelings.", "ja": "遅かれ早かれ、あなたは私の気持ちを理解するだろう。"},
  {"idx": 144, "en": "Can I try on this blue shirt?", "ja": "この青いシャツを試着してもいいですか？"},
  {"idx": 145, "en": "Your bag looks very similar to mine.", "ja": "あなたのバッグは私のものにとても似ている。"},
  {"idx": 146, "en": "He just likes to show off his expensive car.", "ja": "彼は単に高価な車を見せびらかしたいだけだ。"},
  {"idx": 147, "en": "She turned down his invitation to dinner.", "ja": "彼女は彼の夕食への招待を断った。"},
  {"idx": 148, "en": "Please fill out this form with a pen.", "ja": "この用紙にペンで書き込んでください。"},
  {"idx": 149, "en": "The guests were mostly students.", "ja": "客は主に学生たちだった。"},
  {"idx": 150, "en": "My dog decided to dig a hole in the garden.", "ja": "私の犬は庭に穴を掘ることに決めた。"},
  {"idx": 271, "en": "I can't bear this pain any longer.", "ja": "もうこの我慢できない。"},
  {"idx": 272, "en": "It is natural for parents to love their children.", "ja": "親が子どもを愛するのは自然なことだ。"},
  {"idx": 273, "en": "He works in the school administration.", "ja": "彼は学校の運営に関わっている。"},
  {"idx": 274, "en": "The audience cheered loudly for the band.", "ja": "観客はバンドにむけて大声で歓声をあげた。"},
  {"idx": 275, "en": "The company increased its daily production of cars.", "ja": "その会社は車の1日の生産を増やした。"},
  {"idx": 276, "en": "This course will qualify you as a sports coach.", "ja": "このコースはあなたにコーチの資格を与えます。"},
  {"idx": 277, "en": "I have no intention of changing my mind.", "ja": "私は考えを変える意図はありません。"},
  {"idx": 278, "en": "He previously lived in a small apartment.", "ja": "彼は以前は小さなアパートに住んでいた。"},
  {"idx": 279, "en": "English is a very important language.", "ja": "英語はとても重要な言語だ。"},
  {"idx": 280, "en": "You have to pay a membership fee for the club.", "ja": "クラブの会費を払わなければならない。"},
  {"idx": 281, "en": "She doesn't like meat, nor does she like fish.", "ja": "彼女は肉が好きではなく、魚も好きではない。"},
  {"idx": 282, "en": "The peaceful negotiation between the two borders succeeded.", "ja": "二つの国境間の平和的な交渉は成功した。"},
  {"idx": 283, "en": "He works in the automobile industry.", "ja": "彼は自動車産業で働いている。"},
  {"idx": 284, "en": "The old book was covered with dust.", "ja": "その古い本はほこりで覆われていた。"},
  {"idx": 285, "en": "The weather was extremely hot yesterday.", "ja": "昨日の天気は極端に暑かった。"},
  {"idx": 286, "en": "We heard our echo in the dark cave.", "ja": "暗い洞窟で私たちのこだまが聞こえた。"},
  {"idx": 287, "en": "Please give me a detailed map of the city.", "ja": "街の詳細な地図を私にください。"},
  {"idx": 288, "en": "You can stay here for a maximum of three days.", "ja": "最大で3日間ここに滞在できます。"},
  {"idx": 289, "en": "She used a frying pan to cook the eggs.", "ja": "彼女は卵を料理するためにフライパンを使った。"},
  {"idx": 290, "en": "There is room for improvement in your singing.", "ja": "あなたの歌には改善の余地がある。"},
  {"idx": 291, "en": "Many people consider him to be a musical genius.", "ja": "多くの人が彼を音楽の天才だと考えている。"},
  {"idx": 292, "en": "I used my credit card to buy a computer.", "ja": "私はコンピュータを買うためにクレジットカードを使った。"},
  {"idx": 293, "en": "He finally paid off his huge debt.", "ja": "彼はついに巨額の借金を払い終えた。"},
  {"idx": 294, "en": "Water is our most precious natural resource.", "ja": "水は最も貴重な天然資源だ。"},
  {"idx": 295, "en": "She is undergoing physical therapy.", "ja": "彼女は理学療法による治療を受けている。"},
  {"idx": 296, "en": "I took a quick glance at the newspaper.", "ja": "私は新聞を一目見た。"},
  {"idx": 297, "en": "We need more data storage on our computer.", "ja": "私たちのコンピュータにはより多くのデータ保管が必要だ。"},
  {"idx": 298, "en": "He had a very successful academic career.", "ja": "彼はとても成功した大学生活だった。"},
  {"idx": 299, "en": "Does your boss permit you to wear jeans?", "ja": "あなたの上司はジーンズを履くことを許可していますか？"},
  {"idx": 300, "en": "Don't concern yourself with other people's problems.", "ja": "他人の問題について心配しないで。"},
  {"idx": 301, "en": "Try not to strain your delicate eyes in the dark.", "ja": "暗闇で目を張らないようにしなさい。"},
  {"idx": 302, "en": "Diet plays an important role in our health.", "ja": "食事は私たちの健康において重要な役割を果たす。"},
  {"idx": 303, "en": "There was nowhere to sit in the crowded train.", "ja": "混雑した電車の中で座る場所はどこにもなかった。"},
  {"idx": 304, "en": "What is his most recent movie?", "ja": "彼の最新の映画は何ですか？"},
  {"idx": 305, "en": "I met my old school mate at the station.", "ja": "私は駅で古い学校の仲間に会った。"},
  {"idx": 306, "en": "It is difficult to distinguish the twins.", "ja": "双子を区別するのは難しい。"},
  {"idx": 307, "en": "She looks highly sophisticated in that black dress.", "ja": "その黒いドレスを着ると彼女はとても洗練されて見える。"},
  {"idx": 308, "en": "He was very upset when he lost the match.", "ja": "試合に負けた時、彼はとても気持ちが激しく動揺した。"},
  {"idx": 309, "en": "Please do not disturb the sleeping baby.", "ja": "眠っている赤ちゃんの邪魔をしないでください。"},
  {"idx": 310, "en": "They decided to invest their money in a new business.", "ja": "彼らは新しいビジネスにお金を投資することに決めた。"},
  {"idx": 311, "en": "The heat of the sun is very intense here.", "ja": "ここの太陽の熱は非常に激しい。"},
  {"idx": 312, "en": "My grandfather will retire next year.", "ja": "私の祖父は来年引退する。"},
  {"idx": 313, "en": "This park is full of beautiful wildlife.", "ja": "この公園には美しい野生動物がたくさんいる。"},
  {"idx": 314, "en": "He is always polite to older people.", "ja": "彼はいつも年上の人々に対して礼儀正しい。"},
  {"idx": 315, "en": "The clown tried to entertain the children.", "ja": "ピエロは子どもたちを楽しませようとした。"},
  {"idx": 316, "en": "There is strong competition between the two shops.", "ja": "その2つの店の間に強い競争がある。"},
  {"idx": 317, "en": "I will make an inquiry at the office.", "ja": "私はオフィスで問い合わせをするつもりだ。"},
  {"idx": 318, "en": "We had a long period of dry weather.", "ja": "乾燥した天気の長い期間があった。"},
  {"idx": 319, "en": "They used a strong rope to bind the broken boxes.", "ja": "彼らは壊れた箱を束ねるためロープを使った。"},
  {"idx": 320, "en": "I am certain that he will pass the test.", "ja": "私は彼がテストに合格すると確信している。"},
  {"idx": 321, "en": "There were 50 passengers on the train.", "ja": "その電車には50人の乗客がいた。"},
  {"idx": 322, "en": "The teacher praised him for his good behavior.", "ja": "先生は彼の良い振る舞いを褒めた。"},
  {"idx": 323, "en": "The boy was playing outside; meanwhile, his mother prepared dinner.", "ja": "男の子は外で遊んでいた。一方で、母親は夕食の準備をした。"},
  {"idx": 324, "en": "He works hard to earn money for his family.", "ja": "彼は家族のためにお金を稼ぐために一生懸命働く。"},
  {"idx": 325, "en": "Please knock on the door before you enter.", "ja": "入る前にドアをノックしてください。"},
  {"idx": 326, "en": "This puzzle is too complex for me.", "ja": "このパズルは私には複雑すぎる。"},
  {"idx": 327, "en": "The food was terrible; moreover, it was expensive.", "ja": "食べ物はひどかった。その上、値段も高かった。"},
  {"idx": 328, "en": "The structure of the bridge is very strong.", "ja": "その橋の構造は非常に強い。"},
  {"idx": 329, "en": "His loud voice really annoys me.", "ja": "彼の大きな声は本当に私をいらだたせる。"},
  {"idx": 330, "en": "They walked in the opposite direction.", "ja": "彼らは反対の方向へ歩いた。"},
  {"idx": 331, "en": "Television has a strong influence on children.", "ja": "テレビは子どもに強い影響を及ぼす。"},
  {"idx": 332, "en": "The population of the town increased rapidly.", "ja": "町の人口は素早く増加した。"},
  {"idx": 333, "en": "She explained the plan in great detail.", "ja": "彼女は詳細にその計画を説明した。"},
  {"idx": 334, "en": "It is fun to learn about a different culture.", "ja": "異なる文化について学ぶのは楽しい。"},
  {"idx": 335, "en": "I have a prior arrangement at that time.", "ja": "私にはその時間は前の予定がある。"},
  {"idx": 336, "en": "They gathered around the warm fire.", "ja": "彼らは暖かい火の周りに集まった。"},
  {"idx": 337, "en": "The teacher gave an assessment of his progress.", "ja": "先生は彼の進歩の評価を行なった。"},
  {"idx": 338, "en": "He is heavily engaged in business research.", "ja": "彼はビジネスの研究に忙しく従事している。"},
  {"idx": 339, "en": "I really regret turning down his offer.", "ja": "私は彼の申し出を断ったことを後悔している。"},
  {"idx": 340, "en": "She made an excuse for being late.", "ja": "彼女は遅刻したことの言い訳をした。"},
  {"idx": 341, "en": "The criminal was brought to the court.", "ja": "その犯罪者は裁判所に連れて行かれた。"},
  {"idx": 342, "en": "We need to work together to solve this problem.", "ja": "私たちはこの問題を解決するために協力する必要がある。"},
  {"idx": 343, "en": "Pollution threatens the environment.", "ja": "汚染が環境を脅かしている。"},
  {"idx": 344, "en": "This ticket will enable you to enter the museum.", "ja": "このチケットはあなたが博物館に入るのを可能にさせます。"},
  {"idx": 345, "en": "Unfortunately, it rained heavily on the day of the picnic.", "ja": "残念なことに、ピクニックの日は激しい雨が降った。"},
  {"idx": 346, "en": "This painting is a representation of world peace.", "ja": "この絵画は世界平和の表現だ。"},
  {"idx": 347, "en": "Always follow the standard procedure in the lab.", "ja": "実験室では常に標準的な手順に従いなさい。"},
  {"idx": 348, "en": "Our actual performance far exceeded our expectation.", "ja": "実際の成果は私たちの期待をはるかに超えた。"},
  {"idx": 349, "en": "Health is your most valuable asset.", "ja": "健康はあなたの最も価値のある資産だ。"},
  {"idx": 350, "en": "Don't dump your garbage in the beautiful river.", "ja": "その美しい川にゴミを投げ捨てないで。"},
  {"idx": 351, "en": "Every citizen has the right to vote.", "ja": "すべての市民は投票する権利を持っている。"},
  {"idx": 352, "en": "What is your father's main occupation?", "ja": "あなたのお父さんの主な職業は何ですか？"},
  {"idx": 353, "en": "They are trying to restore the old church.", "ja": "彼らは古い教会を修復しようとしている。"},
  {"idx": 354, "en": "He realized the significance of the event.", "ja": "彼はその出来事の重要性を理解した。"},
  {"idx": 355, "en": "The clear river flows into the sea silently.", "ja": "澄んだ川が静かに海へと流れる。"},
  {"idx": 356, "en": "The project ended in a huge failure.", "ja": "そのプロジェクトは大きな失敗に終わった。"},
  {"idx": 357, "en": "His average weekly earnings have increased steadily.", "ja": "彼の週の平均的な稼ぎは着実に増加した。"},
  {"idx": 358, "en": "Heart disease is a major cause of death.", "ja": "心臓の病気は主な死因だ。"},
  {"idx": 359, "en": "He feels pressure from treating his peer groups.", "ja": "彼は同僚のグループと付き合うことにプレッシャーを感じている。"},
  {"idx": 360, "en": "We need an effective strategy to win the game.", "ja": "試合に勝つために効果的な戦略が必要だ。"},
  {"idx": 361, "en": "She has made remarkable progress in her studies.", "ja": "彼女は学習において目立った進歩を遂げた。"},
  {"idx": 362, "en": "The stone hurt the heel of my right foot.", "ja": "その石は右足のかかとを傷つけた。"},
  {"idx": 363, "en": "I will definitely call you back tomorrow.", "ja": "明日絶対にあなたに電話をかけ直します。"},
  {"idx": 364, "en": "It was just an entirely ordinary Monday.", "ja": "それは全くいつもの月曜日だった。"},
  {"idx": 365, "en": "The heavy snow isolated the small village.", "ja": "大雪がその小さな村を孤立させた。"},
  {"idx": 366, "en": "We live in a highly competitive society.", "ja": "私たちは非常に競争力のある社会で生きている。"},
  {"idx": 367, "en": "Are you making any progress with your research?", "ja": "研究で何か進歩を遂げていますか？"},
  {"idx": 368, "en": "This is a typical traditional breakfast in Japan.", "ja": "これは典型的な日本の朝食だ。"},
  {"idx": 369, "en": "Many athletes will compete in the Olympic games.", "ja": "多くの選手がオリンピックで競争するだろう。"},
  {"idx": 370, "en": "He was arrested for physical assault.", "ja": "彼は身体的な暴行で逮捕された。"},
  {"idx": 371, "en": "She spoke with strong faith and deep conviction.", "ja": "彼女は強い信仰と深い信念を持って話した。"},
  {"idx": 372, "en": "I heard a terrible loud noise at night.", "ja": "一晩中ひどく恐ろしい騒音を聞いた。"},
  {"idx": 373, "en": "I received my phone bill in the mail.", "ja": "郵便で電話の請求書を受け取った。"},
  {"idx": 374, "en": "He felt a sharp pain in his chest.", "ja": "彼は胸に鋭い痛みを感じた。"},
  {"idx": 375, "en": "The teacher emphasized the importance of sleep.", "ja": "先生は睡眠の重要性を力説した。"},
  {"idx": 376, "en": "The sunny weather was perfect for walking.", "ja": "晴れた天候は散歩に最適だった。"},
  {"idx": 377, "en": "Many immigrants arrived in the country yesterday.", "ja": "昨日、多くの移民がその国に到着した。"},
  {"idx": 378, "en": "How do you interpret this old complicated poem?", "ja": "あなたはこの古くて複雑な詩をどう解釈しますか？"},
  {"idx": 379, "en": "She was wearing a thick warm winter coat.", "ja": "彼女は厚くて暖かい冬のコートを着ていた。"},
  {"idx": 380, "en": "The rich merchant traveled to many countries.", "ja": "その裕福な商人は多くの国を旅した。"}
];

async function main() {
  const wb = xlsx.readFile(targetFile);
  const ws = wb.Sheets["準2級"];
  const aoa = xlsx.utils.sheet_to_json(ws, { header: 1, defval: "" });

  if (aoa[0][3] !== '例文') aoa[0][3] = '例文';
  if (aoa[0][4] !== '例文訳') aoa[0][4] = '例文訳';

  let appliedCount = 0;
  for (const item of generatedData) {
    // Check if the item matches exactly
    if (aoa[item.idx] && aoa[item.idx][3] === "") {
        aoa[item.idx][3] = item.en;
        aoa[item.idx][4] = item.ja;
        appliedCount++;
    }
  }

  const newWs = xlsx.utils.aoa_to_sheet(aoa);
  wb.Sheets["準2級"] = newWs;
  xlsx.writeFile(wb, outPath);
  console.log(`Successfully applied ${appliedCount} examples. Saved to ${outPath}`);
}

main().catch(console.error);
