const xlsx = require('xlsx');
const fs = require('fs');
const filePath = String.raw`C:\Users\makoto\Documents\GitHub\VocabularyBase\単語リスト\出題頻度順リストのみ_英検英単語.xlsx`;
const outPath = filePath.replace('.xlsx', '_updated.xlsx');
const targetFile = fs.existsSync(outPath) ? outPath : filePath;

const data = [
  {r:601,en:"Most of the students like sports.",ja:"生徒のほとんどはスポーツが好きです。"},
  {r:602,en:"I have little money today.",ja:"今日はお金がほとんどありません。"},
  {r:603,en:"I wonder why he is late.",ja:"彼がなぜ遅れているのか不思議に思います。"},
  {r:604,en:"Many people died in the war.",ja:"その戦争で多くの人々が亡くなりました。"},
  {r:605,en:"My brother is a senior high school student.",ja:"私の兄は年上の（上級の）高校生です。"},
  {r:606,en:"There is a cat on the roof.",ja:"屋根の上に猫がいます。"},
  {r:607,en:"We have to pay a consumption tax.",ja:"私たちは消費税を支払わなければなりません。"},
  {r:608,en:"You should take this medicine after meals.",ja:"食後にこの薬を飲むべきです。"},
  {r:609,en:"The apple dropped from the tree.",ja:"リンゴが木から落ちました。"},
  {r:610,en:"I don't know what to do next.",ja:"次に何をすべきか分かりません。"},
  {r:611,en:"The sun rises in the east.",ja:"太陽は東から昇ります。"},
  {r:612,en:"He is absent from school today.",ja:"彼は今日学校を欠席しています。"},
  {r:613,en:"We must protect the forest ecosystem.",ja:"私たちは森の生態系を守らなければなりません。"},
  {r:614,en:"In the past, many people were illiterate.",ja:"過去には、多くの人々が読み書きができませんでした。"},
  {r:615,en:"If you are in trouble, please call me.",ja:"もし困っているなら、私に電話してください。"},
  {r:616,en:"Please come as soon as possible.",ja:"可能な限り早く来てください。"},
  {r:617,en:"He left the room in a hurry.",ja:"彼は急いで部屋を出ました。"},
  {r:618,en:"Let me introduce my friend to you.",ja:"あなたに私の友達を紹介させてください。"},
  {r:619,en:"They will ban the use of plastic bags.",ja:"彼らはプラスチック袋の使用を禁止するでしょう。"},
  {r:620,en:"My grandfather owns a lot of land.",ja:"私の祖父は多くの土地を所有しています。"},
  {r:621,en:"We went to the beach by car.",ja:"私たちは車で海へ行きました。"},
  {r:622,en:"He is a very creative artist.",ja:"彼はとても創造力のある芸術家です。"},
  {r:623,en:"She wants to study overseas next year.",ja:"彼女は来年外国へ留学したいと思っています。"},
  {r:624,en:"Let's discuss this problem together.",ja:"この問題について一緒に話し合いましょう。"},
  {r:625,en:"The surface of this table is very flat.",ja:"このテーブルの表面はとても平らです。"},
  {r:626,en:"Reading the newspaper is my daily routine.",ja:"新聞を読むことは私の日常の習慣です。"},
  {r:627,en:"I prefer tea to coffee.",ja:"私はコーヒーより紅茶を好みます。"},
  {r:628,en:"He is hopeful about his future.",ja:"彼は自分の将来について希望を持っています。"},
  {r:629,en:"The project is going well so far.",ja:"これまでは、そのプロジェクトは順調に進んでいます。"},
  {r:630,en:"Please answer the questions one by one.",ja:"1つずつ質問に答えてください。"},
  {r:631,en:"It rained all day long yesterday.",ja:"昨日は一日中雨が降りました。"},
  {r:632,en:"Camels can walk in the hot desert.",ja:"ラクダは暑い砂漠を歩くことができます。"},
  {r:633,en:"I am ready for the test tomorrow.",ja:"私は明日のテストの用意ができています。"},
  {r:634,en:"Many large ships arrived at the port.",ja:"多くの大きな船が港に到着しました。"},
  {r:635,en:"He is a researcher of Japanese history.",ja:"彼は日本の歴史の研究者です。"},
  {r:636,en:"She greeted me with a big smile.",ja:"彼女は大きな笑顔で私に挨拶しました。"},
  {r:637,en:"This dictionary belongs to my brother.",ja:"この辞書は私の兄のものです。"},
  {r:638,en:"My dream is to live abroad in the future.",ja:"私の夢は将来海外で生活することです。"},
  {r:639,en:"This new kitchen is very functional.",ja:"この新しいキッチンはとても実用的です。"},
  {r:640,en:"Kyoto is famous for its old temples.",ja:"京都は古いお寺で有名です。"},
  {r:641,en:"We shouldn't waste electricity.",ja:"私たちは電力を無駄にするべきではありません。"},
  {r:642,en:"Let's keep in touch even after graduation.",ja:"卒業した後でも連絡を取り合いましょう。"},
  {r:643,en:"The tree has beautiful green leaves.",ja:"その木には美しい緑の葉があります。"},
  {r:644,en:"They will establish a new school next year.",ja:"彼らは来年新しい学校を設立します。"},
  {r:645,en:"I want to climb Mt. Fuji someday.",ja:"いつか富士山に登りたいです。"},
  {r:646,en:"His magic tricks always amaze everyone.",ja:"彼の手品はいつもみんなをびっくりさせます。"},
  {r:647,en:"There is a beautiful river in the valley.",ja:"その谷には美しい川があります。"},
  {r:648,en:"We will have lunch at noon.",ja:"私たちは正午に昼食を食べます。"},
  {r:649,en:"The good food satisfied all the guests.",ja:"そのおいしい食べ物はすべての客を満足させました。"},
  {r:650,en:"Trucks transport many goods every day.",ja:"トラックは毎日多くの品物を輸送します。"},
  {r:651,en:"Every human being makes mistakes.",ja:"すべての人間は間違いをします。"},
  {r:652,en:"The cold wind began to blow.",ja:"冷たい風が吹き始めました。"},
  {r:653,en:"Believe it or not, I saw a UFO yesterday.",ja:"信じられないだろうけど、昨日UFOを見たんだ。"},
  {r:654,en:"We have a monthly meeting at school.",ja:"学校で月に1回の会議があります。"},
  {r:655,en:"He can run 100 meters in 12 seconds.",ja:"彼は100メートルを12秒で走ることができます。"},
  {r:656,en:"It's sunny, so let's get out and play.",ja:"晴れているから、外へ出て遊びましょう。"},
  {r:657,en:"Although it was raining, we went shopping.",ja:"雨が降っていたけれど、私たちは買い物に行きました。"},
  {r:658,en:"This beautiful dress is made of silk.",ja:"この美しいドレスは絹でできています。"},
  {r:659,en:"Pandas are endangered animals.",ja:"パンダは絶滅の危機にさらされている動物です。"},
  {r:660,en:"Living near the station is very convenient.",ja:"駅の近くに住むのはとても便利です。"},
  {r:661,en:"We played basketball in the gym.",ja:"私たちは体育館でバスケットボールをしました。"},
  {r:662,en:"Please go ahead, I will follow you later.",ja:"先に行ってください、私は後からついていきます。"},
  {r:663,en:"My grandfather breeds dogs at his farm.",ja:"私の祖父は農場で犬を飼育しています。"},
  {r:664,en:"She wrapped the present in beautiful paper.",ja:"彼女はプレゼントを美しい紙で包みました。"},
  {r:665,en:"The number of students will increase next year.",ja:"来年、生徒の数は増えるでしょう。"},
  {r:666,en:"He works for a railway company.",ja:"彼は鉄道会社で働いています。"},
  {r:667,en:"I like English. On the other hand, my brother likes math.",ja:"私は英語が好きです。一方で、私の兄は数学が好きです。"},
  {r:668,en:"My bag is heavy, so my shoulder hurts.",ja:"カバンが重いので、私の肩が痛いです。"},
  {r:669,en:"The town gets its water supply from a nearby lake.",ja:"その町は近くの湖から水の供給を得ています。"},
  {r:670,en:"According to the weather forecast, it will rain tomorrow.",ja:"天気予報によれば、明日は雨が降るそうです。"},
  {r:671,en:"He will lead the team to victory.",ja:"彼はチームを勝利へと導くでしょう。"},
  {r:672,en:"Today is a national holiday.",ja:"今日は国家の休日（国民の祝日）です。"},
  {r:673,en:"Could you do me a favor?",ja:"頼み事を聞いて（お願いを聞いて）いただけませんか？"},
  {r:674,en:"My right foot hurts.",ja:"右の足が痛いです。"},
  {r:675,en:"Let's get some take out for dinner.",ja:"夕食に何か持ち帰り（テイクアウト）を買いましょう。"},
  {r:676,en:"We conducted a survey about students' favorite subjects.",ja:"私たちは生徒の好きな科目についての調査を行いました。"},
  {r:677,en:"Birds fly south in the winter.",ja:"鳥たちは冬には南へ飛びます。"},
  {r:678,en:"My parents let me go to the party.",ja:"両親は私をパーティーに行かせてくれました。"},
  {r:679,en:"I left early so that I wouldn't be late.",ja:"遅刻しないように（するために）、私は早く出発しました。"},
  {r:680,en:"What sort of music do you listen to?",ja:"どんな種類の音楽を聴きますか？"},
  {r:681,en:"We will arrive at the station at ten o'clock.",ja:"私たちは10時に駅に到着します。"},
  {r:682,en:"It takes about 15 minutes to go to school on foot.",ja:"学校まで歩いて行くのに約15分かかります。"},
  {r:683,en:"The queen wore a beautiful jewel.",ja:"女王は美しい宝石を身につけていました。"},
  {r:684,en:"He fell in love with her at first sight.",ja:"彼は一目で彼女に恋をしました。"},
  {r:685,en:"Though he is young, he is very smart.",ja:"彼は若いだけれども、とても賢いです。"},
  {r:686,en:"These animals are in danger of extinction.",ja:"これらの動物は絶滅の危険にさらされています。"},
  {r:687,en:"He found a dead bird in the garden.",ja:"彼は庭で死んだ鳥を見つけました。"},
  {r:688,en:"There were about a hundred people in the hall.",ja:"ホールには約百人の人々がいました。"},
  {r:689,en:"It is a very good book indeed.",ja:"それは実に良い本です。"},
  {r:690,en:"The government is trying to improve the economy.",ja:"政府は経済を改善しようとしています。"},
  {r:691,en:"My grandparents live in the countryside.",ja:"私の祖父母は田舎に住んでいます。"},
  {r:692,en:"He drank a large amount of water.",ja:"彼は大量の水（多くの量の水）を飲みました。"},
  {r:693,en:"We have a limited amount of time.",ja:"私たちには限られた量の時間しかありません。"},
  {r:694,en:"Japan has a mild climate.",ja:"日本は穏やかな気候です。"},
  {r:695,en:"The elevator is out of order today.",ja:"今日はエレベーターが故障しています。"},
  {r:696,en:"We must respect human rights.",ja:"私たちは人権を尊重しなければなりません。"},
  {r:697,en:"A high wall surrounds the castle.",ja:"高い壁がその城を囲んでいます。"},
  {r:698,en:"This temple is a holy place for them.",ja:"このお寺は彼らにとって神聖な場所です。"},
  {r:699,en:"Please read the instructions carefully.",ja:"注意深く指示を読んでください。"},
  {r:700,en:"Playing games all day is a waste of time.",ja:"一日中ゲームをすることは時間の浪費です。"},
  {r:701,en:"Many animals cannot survive in the cold winter.",ja:"多くの動物は寒い冬を生き残ることができません。"},
  {r:702,en:"I read a weekly magazine.",ja:"私は週刊の雑誌を読みます。"},
  {r:703,en:"There is a beautiful picture on the wall.",ja:"壁に美しい絵があります。"},
  {r:704,en:"The train is about to leave.",ja:"電車は出発する直前です。"},
  {r:705,en:"I bought a fashion magazine at the bookstore.",ja:"本屋でファッション雑誌を買いました。"},
  {r:706,en:"Squirrels store nuts for the winter.",ja:"リスは冬のために木の実を蓄えます。"},
  {r:707,en:"What is your opinion about this problem?",ja:"この問題についてのあなたの意見は何ですか？"},
  {r:708,en:"It rained day after day.",ja:"毎日雨が降りました。"},
  {r:709,en:"Don't be so lazy. Clean your room.",ja:"そんなに怠け者にならないで。部屋を掃除しなさい。"},
  {r:710,en:"We must stop discrimination against women.",ja:"私たちは女性に対する差別をなくさなければなりません。"},
  {r:711,en:"The tree has very deep roots.",ja:"その木はとても深い根を持っています。"},
  {r:712,en:"Please fold the paper in half.",ja:"紙を半分に折ってください。"},
  {r:713,en:"It's raining. Even so, I have to go out.",ja:"雨が降っています。それでも、私は出かけなければなりません。"},
  {r:714,en:"Are you afraid of the dark?",ja:"あなたは暗闇を恐れていますか？"},
  {r:715,en:"I am a little bit tired today.",ja:"今日は少し疲れています。"},
  {r:716,en:"He has traveled all over the world.",ja:"彼は世界の至る所に（世界中を）旅行しました。"},
  {r:717,en:"The town is planning the development of a new park.",ja:"その町は新しい公園の開発を計画しています。"},
  {r:718,en:"Steam is coming out of the kettle.",ja:"やかんから蒸気が出ています。"},
  {r:719,en:"It was foolish of me to believe his story.",ja:"彼の話を信じたなんて、私は愚かでした。"},
  {r:720,en:"I feel a sharp pain in my stomach.",ja:"胃に鋭い痛みを感じます。"},
  {r:721,en:"How long does it take from here to the station?",ja:"ここから駅までどのくらいかかりますか？"},
  {r:722,en:"They use dangerous chemicals in that factory.",ja:"あの工場では危険な化学物質を使っています。"},
  {r:723,en:"Let's check out that new restaurant.",ja:"あの新しいレストランを調査して（調べて）みましょう。"},
  {r:724,en:"She said she was busy today.",ja:"彼女は今日忙しいと言いました。"},
  {r:725,en:"The police finally captured the thief.",ja:"警察はついに泥棒を捕まえました。"},
  {r:726,en:"She made a paper crane for world peace.",ja:"彼女は世界平和のために折り鶴を作りました。"},
  {r:727,en:"This book is concerned with the environment.",ja:"この本は環境に関係しています。"},
  {r:728,en:"I am sick of the hot weather.",ja:"私は暑い天気にうんざりしています。"},
  {r:729,en:"I saw a tiny bird in the garden.",ja:"庭で小さな鳥を見ました。"},
  {r:730,en:"My shoes are wet from the rain.",ja:"私の靴は雨で濡れています。"},
  {r:731,en:"I hope you get over your cold soon.",ja:"早く風邪を乗りこえる（治る）ことを願っています。"},
  {r:732,en:"The police arrested the man.",ja:"警察はその男を逮捕しました。"},
  {r:733,en:"Children are always curious about everything.",ja:"子供たちはいつも何にでも好奇心が強いです。"},
  {r:734,en:"My parents encourage me to study hard.",ja:"両親は私に一生懸命勉強するように促します。"},
  {r:735,en:"I get along with my new classmates.",ja:"私は新しいクラスメイトとうまくやっています。"},
  {r:736,en:"It is unfair to treat them differently.",ja:"彼らを違うように扱うのは不公平です。"},
  {r:737,en:"I heard a strange noise last night.",ja:"昨夜、奇妙な音を聞きました。"},
  {r:738,en:"Please listen to me carefully.",ja:"注意深く私の話を聞いてください。"},
  {r:739,en:"I was very tired after the long trip.",ja:"長い旅行の後で私はとても疲れていました。"},
  {r:740,en:"Let's take a rest under the tree.",ja:"木の下で休憩しましょう。"},
  {r:741,en:"I have a terrible headache today.",ja:"今日はひどい頭痛がします。"},
  {r:742,en:"I hope to visit London again.",ja:"またロンドンを訪れたいと思います。"},
  {r:743,en:"She didn't accept my invitation.",ja:"彼女は私の招待を受け入れませんでした。"},
  {r:744,en:"We saw the Statue of Liberty in New York.",ja:"私たちはニューヨークで自由の女神像を見ました。"},
  {r:745,en:"Is there anything else you want to say?",ja:"その他に何か言いたいことはありますか？"},
  {r:746,en:"You must obey the law.",ja:"法律を守らなければなりません。"},
  {r:747,en:"Please check out this website.",ja:"このウェブサイトを確認してみてください。"},
  {r:748,en:"I bought some notebooks at the stationery shop.",ja:"私は文房具店でノートを何冊か買いました。"},
  {r:749,en:"They are building a new house on this site.",ja:"彼らはこの場所に新しい家を建てています。"},
  {r:750,en:"Please hand out these papers to everyone.",ja:"これらの紙をみんなに配ってください。"},
  {r:751,en:"We are searching for the lost dog.",ja:"私たちは迷子の犬を探索しています（探しています）。"},
  {r:752,en:"It was a difficult decision for him.",ja:"彼にとってそれは難しい決定でした。"},
  {r:753,en:"He practiced playing the piano day in, day out.",ja:"彼は来る日も来る日もピアノを弾く練習をしました。"},
  {r:754,en:"Can you explain your plan in detail?",ja:"あなたの計画を詳細に説明してくれますか？"},
  {r:755,en:"The town has seen a rapid population growth.",ja:"その町は急速な人口の増加を見せています。"},
  {r:756,en:"I need some new stationery for school.",ja:"学校のために新しい文房具がいくつか必要です。"},
  {r:757,en:"Read the sentences above.",ja:"上記の文を読みなさい。"},
  {r:758,en:"I can't stand this hot weather.",ja:"私はこの暑い天気をがまんできません。"},
  {r:759,en:"I haven't finished my homework yet.",ja:"私はまだ宿題を終えていません。"},
  {r:760,en:"Does the price include tax?",ja:"その値段は税金を含んでいますか？"},
  {r:761,en:"She held the baby in her arms.",ja:"彼女は赤ちゃんを腕に抱きました（握りました）。"},
  {r:762,en:"Plants absorb carbon dioxide.",ja:"植物は二酸化炭素を吸収します。"},
  {r:763,en:"Did you hear from him recently?",ja:"最近彼から連絡がありましたか？"},
  {r:764,en:"This rule applies to everyone.",ja:"このルールは全員に当てはまります。"},
  {r:765,en:"He is old enough to drive a car.",ja:"彼は車を運転するのに十分な年齢です。"},
  {r:766,en:"I wake up at six every morning.",ja:"私は毎朝6時に目が覚めます。"},
  {r:767,en:"Plants depend on water to grow.",ja:"植物が育つには水に依存します。"},
  {r:768,en:"The atomic bomb fell on Hiroshima in 1945.",ja:"1945年に広島に原子爆弾が落ちました。"},
  {r:769,en:"He is a resident of this apartment.",ja:"彼はこのアパートの居住者です。"},
  {r:770,en:"The audience enjoyed the concert very much.",ja:"聴衆（観客）はそのコンサートをとても楽しみました。"},
  {r:771,en:"The brave firefighter saved the child.",ja:"その勇敢な消防士が子供を救いました。"},
  {r:772,en:"Do you know how to use a fire extinguisher?",ja:"消火器の使い方を知っていますか？"},
  {r:773,en:"This gate is made of iron.",ja:"この門は鉄でできています。"},
  {r:774,en:"It is likely to rain tomorrow.",ja:"明日は雨が降る可能性が高いです。"},
  {r:775,en:"Japan does a lot of trade with America.",ja:"日本はアメリカとたくさんの貿易をしています。"},
  {r:776,en:"Don't run in the hall.",ja:"廊下を走ってはいけません。"},
  {r:777,en:"The old house is in need of repair.",ja:"その古い家は修理を必要としています。"},
  {r:778,en:"Please stand up when the teacher comes in.",ja:"先生が入ってきたら立ってください。"},
  {r:779,en:"Please fill in this form.",ja:"この用紙に必要事項を記入してください。"},
  {r:780,en:"London is the capital of the UK.",ja:"ロンドンはイギリスの首都です。"},
  {r:781,en:"He is a very kind person.",ja:"彼はとても親切な人です。"},
  {r:782,en:"She runs a small cafe.",ja:"彼女は小さなカフェを主催（経営）しています。"},
  {r:783,en:"How was your flight to New York?",ja:"ニューヨークへの飛行（フライト）はどうでしたか？"},
  {r:784,en:"We got lost in the big forest.",ja:"私たちは大きな森の中で道に迷いました。"},
  {r:785,en:"Solar power is a renewable energy source.",ja:"太陽光は再生可能なエネルギー源です。"},
  {r:786,en:"He plays video games all the time.",ja:"彼は常にビデオゲームをしています。"},
  {r:787,en:"I wrote a poem for my mother.",ja:"私は母のために詩を書きました。"},
  {r:788,en:"I asked him for help.",ja:"私は彼に助けを求めました。"},
  {r:789,en:"I want to donate some money to the hospital.",ja:"私は病院にいくらかのお金を寄付したいです。"},
  {r:790,en:"The class will begin soon.",ja:"授業はまもなく始まります。"},
  {r:791,en:"A bird made a nest in the tree.",ja:"鳥が木に巣を作りました。"},
  {r:792,en:"He is known as a great scientist.",ja:"彼は偉大な科学者として知られています。"},
  {r:793,en:"Japan imports oil from other countries.",ja:"日本は他の国から石油を輸入しています。"},
  {r:794,en:"Can you keep a secret?",ja:"秘密を守れますか？"},
  {r:795,en:"This book was given to me by my uncle.",ja:"この本は叔父によって私に与えられました。"},
  {r:796,en:"You are making good progress in English.",ja:"あなたは英語で良い進歩をしています。"},
  {r:797,en:"I have some unused stamps.",ja:"未使用の切手がいくつかあります。"},
  {r:798,en:"Neither my brother nor I can play the piano.",ja:"兄も私もピアノを弾くことができません。"},
  {r:799,en:"The project was successful as a whole.",ja:"そのプロジェクトは全体として成功でした。"},
  {r:800,en:"I'd like a hamburger to go, please.",ja:"ハンバーガーを持ち帰りでお願いします。"},
];

async function main() {
  const wb = xlsx.readFile(targetFile);
  const ws = wb.Sheets["3級"];
  const aoa = xlsx.utils.sheet_to_json(ws, { header: 1, defval: "" });
  let c = 0;
  for (const item of data) {
    const idx = item.r;
    if (aoa[idx] && aoa[idx][3] === "") { aoa[idx][3] = item.en; aoa[idx][4] = item.ja; c++; }
  }
  const newWs = xlsx.utils.aoa_to_sheet(aoa);
  wb.Sheets["3級"] = newWs;
  xlsx.writeFile(wb, outPath);
  console.log(`Applied ${c} examples (601-800). Saved.`);
}
main().catch(console.error);
