const xlsx = require('xlsx');
const fs = require('fs');
const filePath = String.raw`C:\Users\makoto\Documents\GitHub\VocabularyBase\単語リスト\出題頻度順リストのみ_英検英単語.xlsx`;
const outPath = filePath.replace('.xlsx', '_updated.xlsx');
const targetFile = fs.existsSync(outPath) ? outPath : filePath;

const data = [
  {r:1,en:"Kyoto is a famous city in Japan.",ja:"京都は日本で有名な都市です。"},
  {r:2,en:"What are you going to do this weekend?",ja:"今週末は何をする予定ですか？"},
  {r:3,en:"Summer vacation will start soon.",ja:"夏休みがまもなく始まります。"},
  {r:4,en:"It is still raining outside.",ja:"外はまだ雨が降っています。"},
  {r:5,en:"Baseball is a very popular sport in my school.",ja:"野球は私の学校でとても人気のスポーツです。"},
  {r:6,en:"I practice the piano every day.",ja:"私は毎日ピアノを練習します。"},
  {r:7,en:"He read a lot of books during the summer vacation.",ja:"彼は夏休みの間にたくさんの本を読みました。"},
  {r:8,en:"I enjoyed talking with my friends.",ja:"私は友達と話すのを楽しみました。"},
  {r:9,en:"My favorite subject is science.",ja:"私のお気に入りの科目は理科です。"},
  {r:10,en:"They sell many kinds of fruits at that store.",ja:"あの店ではたくさんの種類の果物を売っています。"},
  {r:11,en:"Please bring your dictionary to the next class.",ja:"次の授業に辞書を持って来てください。"},
  {r:12,en:"This computer is too expensive for me to buy.",ja:"このコンピューターは私には高価すぎて買えません。"},
  {r:13,en:"I want to join the tennis club.",ja:"私はテニス部に参加したいです。"},
  {r:14,en:"The movie was so interesting.",ja:"その映画はとてもおもしろかったです。"},
  {r:15,en:"What time does the train leave the station?",ja:"その電車は何時に駅を出発しますか（去りますか）？"},
  {r:16,en:"I don't have enough time to eat breakfast.",ja:"私には朝食を食べる十分な時間がありません。"},
  {r:17,en:"What happened to your bicycle?",ja:"あなたの自転車に何が起きたのですか？"},
  {r:18,en:"Her bag is different from mine.",ja:"彼女のカバンは私のものと違います。"},
  {r:19,en:"I will invite him to my birthday party.",ja:"彼を私の誕生日パーティーに招待します。"},
  {r:20,en:"I like music. How about you?",ja:"私は音楽が好きです。あなたはどうですか？"},
  {r:21,en:"We plan to go to Hokkaido next month.",ja:"私たちは来月北海道へ行くことを計画しています。"},
  {r:22,en:"May I ask you a question?",ja:"あなたに質問をたずねてもいいですか？"},
  {r:23,en:"Please wait here until I come back.",ja:"私が戻ってくるまでここで待っていてください。"},
  {r:24,en:"Dinner is almost ready.",ja:"夕食の準備がほとんどできました。"},
  {r:25,en:"My sister is sick in bed today.",ja:"私の妹は今日、病気で寝込んでいます。"},
  {r:26,en:"We were excited to hear the good news.",ja:"私たちはその良い知らせを聞いて興奮しました。"},
  {r:27,en:"Mr. Smith teaches us science.",ja:"スミス先生は私たちに科学（理科）を教えます。"},
  {r:28,en:"I study in the library after school.",ja:"私は放課後、図書館で勉強します。"},
  {r:29,en:"I want to visit London someday.",ja:"いつかロンドンを訪問したいです。"},
  {r:30,en:"This T-shirt is very cheap.",ja:"このTシャツはとても安いです。"},
  {r:31,en:"I was taking a bath then.",ja:"私はそのときお風呂に入っていました。"},
  {r:32,en:"Please show me your pictures.",ja:"あなたの写真を私に見せてください。"},
  {r:33,en:"It rained, so we played cards instead.",ja:"雨が降ったので、そのかわりに私たちはトランプをしました。"},
  {r:34,en:"What about going to the park?",ja:"公園に行くのはどうですか？"},
  {r:35,en:"There are many beautiful flowers in the garden.",ja:"庭には美しい花がたくさんあります。"},
  {r:36,en:"What are you looking for?",ja:"あなたは何を探しているのですか？"},
  {r:37,en:"Let's meet at the station at ten.",ja:"10時に駅で会いましょう。"},
  {r:38,en:"I was late for school because of the heavy snow.",ja:"大雪のために私は学校に遅れました。"},
  {r:39,en:"He is sitting by the window.",ja:"彼は窓のそばに座っています。"},
  {r:40,en:"Did you enjoy your stay in Japan?",ja:"日本での滞在は楽しみましたか？"},
  {r:41,en:"I hope to see you again.",ja:"またあなたにお会いできることを望んでいます。"},
  {r:42,en:"This cake is very delicious.",ja:"このケーキはとてもおいしいです。"},
  {r:43,en:"Let's play baseball together.",ja:"一緒に野球をしましょう。"},
  {r:44,en:"We decided to help him.",ja:"私たちは彼を手伝うことを決心しました。"},
  {r:45,en:"I will call you later.",ja:"後であなたに電話します。"},
  {r:46,en:"There is a big festival in our town every summer.",ja:"私たちの町では毎年夏に大きな祭りがあります。"},
  {r:47,en:"I went to Okinawa during the winter vacation.",ja:"私は冬の休暇中に沖縄に行きました。"},
  {r:48,en:"I have my own computer.",ja:"私は自分のコンピューターを持っています。"},
  {r:49,en:"Let's eat lunch at noon.",ja:"正午に昼食を食べましょう。"},
  {r:50,en:"This is a very important test.",ja:"これはとても重要なテストです。"},
  {r:51,en:"I can't remember his name.",ja:"彼の名前を思い出せません。"},
  {r:52,en:"I always get nervous before a test.",ja:"テストの前はいつもあがってしまいます。"},
  {r:53,en:"Look at that beautiful bird.",ja:"あの美しい鳥を見て。"},
  {r:54,en:"The weather is very good today.",ja:"今日は天気がとても良いです。"},
  {r:55,en:"There is a tall tree in front of my house.",ja:"私の家の前に高い木があります。"},
  {r:56,en:"I have to do my homework now.",ja:"私は今、宿題をしなければなりません。"},
  {r:57,en:"My grandfather grows vegetables in his garden.",ja:"私の祖父は庭で野菜を育てています。"},
  {r:58,en:"Can you help me carry this box?",ja:"この箱を運ぶのを手伝ってくれませんか？"},
  {r:59,en:"This bag is too heavy for me.",ja:"このカバンは私には重すぎます。"},
  {r:60,en:"You need to sleep well tonight.",ja:"あなたは今夜よく眠る必要があります。"},
  {r:61,en:"I have a lot of things to do today.",ja:"今日はやらなければならないことがたくさんあります。"},
  {r:62,en:"Are you sure about that?",ja:"それについて確信していますか？"},
  {r:63,en:"What time will he arrive at the station?",ja:"彼は何時に駅に到着しますか？"},
  {r:64,en:"Look at the building over there.",ja:"あそこの建物を見てください。"},
  {r:65,en:"May I borrow your pen?",ja:"あなたのペンを借りてもいいですか？"},
  {r:66,en:"This park is a good place to read books.",ja:"この公園は本を読のむのに良い場所です。"},
  {r:67,en:"Don't break that window.",ja:"その窓を壊さないでください。"},
  {r:68,en:"My birthday is in June.",ja:"私の誕生日は6月です。"},
  {r:69,en:"I usually get up at six.",ja:"私は普通は6時に起きます。"},
  {r:70,en:"I hope our team will win the game.",ja:"私たちのチームが試合に勝つことを望んでいます。"},
  {r:71,en:"Eating vegetables is healthy.",ja:"野菜を食べることは健康に良いです。"},
  {r:72,en:"Look at the traffic sign.",ja:"交通標識を見てください。"},
  {r:73,en:"One day, I want to go to space.",ja:"ある日（いつか）、宇宙に行きたいです。"},
  {r:74,en:"Maybe it will rain tomorrow.",ja:"たぶん明日は雨が降るでしょう。"},
  {r:75,en:"How often do you play tennis?",ja:"どのぐらいの頻度でテニスをしますか？"},
  {r:76,en:"He fell down and hurt his leg.",ja:"彼は転んで脚を痛めました。"},
  {r:77,en:"Please use a dictionary to find the word.",ja:"単語を見つけるために辞書を使ってください。"},
  {r:78,en:"Put your bag on the desk.",ja:"机の上にカバンを置いてください。"},
  {r:79,en:"Can I try on this shirt?",ja:"このシャツを試着してもいいですか？"},
  {r:80,en:"This math problem is very difficult.",ja:"この数学の問題はとても難しいです。"},
  {r:81,en:"I am interested in Japanese history.",ja:"私は日本の歴史に興味があります。"},
  {r:82,en:"I was watching TV when he came home.",ja:"彼が帰宅したとき、私はテレビを見ていました。"},
  {r:83,en:"Come and sit beside me.",ja:"来て、私の横に座りなさい。"},
  {r:84,en:"My brother is very strong.",ja:"私の兄はとても強いです。"},
  {r:85,en:"I believe you.",ja:"私はあなたを信じます。"},
  {r:86,en:"I was sad to hear the news.",ja:"その知らせを聞いて悲しかったです。"},
  {r:87,en:"You should go to bed early.",ja:"あなたは早く寝るべきです。"},
  {r:88,en:"Look at the clock on the wall.",ja:"壁の時計を見てください。"},
  {r:89,en:"The population of this city is about one million.",ja:"この市の人口は約100万です。"},
  {r:90,en:"The sun is very bright today.",ja:"今日は太陽がとても明るいです。"},
  {r:91,en:"Let's try again.",ja:"もう一度やってみましょう。"},
  {r:92,en:"I can hear the birds singing.",ja:"鳥が歌っているのが聞こえます。"},
  {r:93,en:"I look forward to seeing you.",ja:"あなたにお会いするのを楽しみにしています。"},
  {r:94,en:"My father likes to cook on weekends.",ja:"私の父は週末に料理をするのが好きです。"},
  {r:95,en:"Can you drive a car?",ja:"あなたは車を運転できますか？"},
  {r:96,en:"Please wash your face.",ja:"顔を洗ってください。"},
  {r:97,en:"Where did you get that ticket?",ja:"どこでそのチケットを得た（手に入れた）のですか？"},
  {r:98,en:"I can't find my keys.",ja:"私の鍵を見つけることができません。"},
  {r:99,en:"We went fishing in the lake.",ja:"私たちは湖に釣りに行きました。"},
  {r:100,en:"I am really tired today.",ja:"私は今日、本当に疲れています。"},
  {r:101,en:"I sometimes play soccer with my friends.",ja:"私は時々友達とサッカーをします。"},
  {r:102,en:"The soccer game was very exciting.",ja:"そのサッカーの試合はとても興奮するものでした（ワクワクしました）。"},
  {r:103,en:"I will write a letter to my grandmother.",ja:"私は祖母に手紙を書くつもりです。"},
  {r:104,en:"My mother makes delicious sandwiches.",ja:"私の母はおいしいサンドイッチを作ります。"},
  {r:105,en:"He is the tallest boy in our class.",ja:"彼は私たちのクラスで一番背が高い男の子です。"},
  {r:106,en:"Can you guess what is in this box?",ja:"この箱の中に何が入っているか推測できますか？"},
  {r:107,en:"The station is between the bank and the park.",ja:"駅は銀行と公園の間にあります。"},
  {r:108,en:"We have summer vacation in July.",ja:"私たちは7月に夏休みがあります。"},
  {r:109,en:"You can find useful information on the internet.",ja:"インターネットで役立つ情報を見つけることができます。"},
  {r:110,en:"I will pay for the lunch.",ja:"私が昼食代を支払います。"},
  {r:111,en:"Spring is my favorite season.",ja:"春は私のお気に入りの季節です。"},
  {r:112,en:"I have already finished my homework.",ja:"私はもう宿題を終えました。"},
  {r:113,en:"Tickets for the concert are sold out.",ja:"そのコンサートのチケットは売り切れです。"},
  {r:114,en:"She takes care of her little brother.",ja:"彼女は弟の面倒を見ています。"},
  {r:115,en:"The graduation ceremony is in March.",ja:"卒業式は3月にあります。"},
  {r:116,en:"It's cold outside, so you should wear a coat.",ja:"外は寒いので、コートを着るべきです。"},
  {r:117,en:"He studies science at the university.",ja:"彼は大学で科学を勉強しています。"},
  {r:118,en:"I have a math test tomorrow.",ja:"明日は数学のテストがあります。"},
  {r:119,en:"There were many people in the park.",ja:"公園には多くの人々がいました。"},
  {r:120,en:"She has lots of books in her room.",ja:"彼女の部屋にはたくさんの本があります。"},
  {r:121,en:"You must take care when you cross the street.",ja:"道を渡る時は注意しなければなりません。"},
  {r:122,en:"Who invented the telephone?",ja:"誰が電話を発明したのですか？"},
  {r:123,en:"He lives in a large house.",ja:"彼は大きな家に住んでいます。"},
  {r:124,en:"My sister will get married next month.",ja:"私の姉は来月結婚します。"},
  {r:125,en:"The city hall is near the station.",ja:"市庁舎は駅の近くにあります。"},
  {r:126,en:"I have to go to the bank to get some money.",ja:"お金をおろすために銀行に行かなければなりません。"},
  {r:127,en:"She won the first prize in the contest.",ja:"彼女はコンテストで一等賞をとりました。"},
  {r:128,en:"I am trying to save money to buy a new bike.",ja:"私は新しい自転車を買うためにお金を節約しよう（貯めよう）としています。"},
  {r:129,en:"I usually play tennis on weekends.",ja:"私は普通、週末にテニスをします。"},
  {r:130,en:"I want to buy some new clothes.",ja:"私は新しい服を買いたいです。"},
  {r:131,en:"We went to the art museum last Sunday.",ja:"私たちはこの前の日曜日に美術館に行きました。"},
  {r:132,en:"I was born in Tokyo in 2005.",ja:"私は2005年に東京で生まれました。"},
  {r:133,en:"You can choose any color you like.",ja:"好きな色をどれでも選ぶことができます。"},
  {r:134,en:"My cousin lives in Canada.",ja:"私のいとこはカナダに住んでいます。"},
  {r:135,en:"I looked everywhere for my keys.",ja:"鍵を探してどこでも見ました。"},
  {r:136,en:"This plant needs a lot of water.",ja:"この植物はたくさんの水が必要です。"},
  {r:137,en:"I will try to finish it by tomorrow.",ja:"明日までにそれを終わらせるように試してみます（努力します）。"},
  {r:138,en:"If it is sunny tomorrow, let's go to the beach.",ja:"もし明日晴れなら、海へ行きましょう。"},
  {r:139,en:"Can I have another cup of tea?",ja:"もう一杯お茶をもらえますか？"},
  {r:140,en:"Will you take part in the sports festival?",ja:"あなたは体育祭に参加しますか？"},
  {r:141,en:"What is the meaning of this word?",ja:"この単語の意味は何ですか？"},
  {r:142,en:"He hit the ball very hard.",ja:"彼はとても強くボールを打ちました。"},
  {r:143,en:"My mother was angry because I broke the window.",ja:"私が窓を割ったので、母は怒っていました。"},
  {r:144,en:"We used a map to find the station.",ja:"私たちは駅を見つけるために地図を使いました。"},
  {r:145,en:"I am proud of my brother.",ja:"私は兄を誇りに思っています。"},
  {r:146,en:"Wash your hands if they are dirty.",ja:"手が汚いなら洗いなさい。"},
  {r:147,en:"They love each other.",ja:"彼らはお互いに愛し合っています。"},
  {r:148,en:"You must keep your promise.",ja:"約束を守らなければなりません。"},
  {r:149,en:"Can you solve this math problem?",ja:"あなたはこの数学の問題を解くことができますか？"},
  {r:150,en:"Who is that man standing there?",ja:"あそこに立っているあの男の人はだれですか？"},
  {r:151,en:"What are you doing now?",ja:"あなたは今何をしていますか？"},
  {r:152,en:"How do you go to school?",ja:"あなたはどのように（どうやって）学校に行きますか？"},
  {r:153,en:"That restaurant has many customers.",ja:"あのレストランにはたくさんの顧客がいます。"},
  {r:154,en:"I went to Hokkaido once.",ja:"私はかつて（一度）北海道に行ったことがあります。"},
  {r:155,en:"I brush my teeth twice a day.",ja:"私は1日に2回歯を磨きます。"},
  {r:156,en:"Please pass me the salt.",ja:"私に塩を取ってください。"},
  {r:157,en:"Hurry up, or you will be late.",ja:"急いで、そうしないと遅れますよ。"},
  {r:158,en:"Did you notice the sign on the wall?",ja:"壁の標識に気づきましたか？"},
  {r:159,en:"My brother likes to collect foreign stamps.",ja:"私の兄は外国の切手を集めるのが好きです。"},
  {r:160,en:"I saw a traffic accident yesterday.",ja:"私は昨日、交通事故を見ました。"},
  {r:161,en:"There are more than forty students in my class.",ja:"私のクラスには40人より多い（40人以上の）生徒がいます。"},
  {r:162,en:"How much does this book cost?",ja:"この本はいくら費用がかかりますか？"},
  {r:163,en:"Look at the stars in the sky.",ja:"空の星を見てください。"},
  {r:164,en:"Please keep this room clean.",ja:"この部屋をきれいに保ってください。"},
  {r:165,en:"He was late for school today.",ja:"彼は今日学校に遅れました。"},
  {r:166,en:"It is very cold outside today.",ja:"今日は外がとても冷たい（寒い）です。"},
  {r:167,en:"Do you like Italian food?",ja:"イタリアの食べ物は好きですか？"},
  {r:168,en:"Are you ready to order?",ja:"注文する準備はできましたか？"},
  {r:169,en:"This room is always very clean.",ja:"この部屋はいつもとてもきれいです。"},
  {r:170,en:"I will do my homework right away.",ja:"私は直ちに宿題をやります。"},
  {r:171,en:"How was your trip to Kyoto?",ja:"京都への旅行はどうでしたか？"},
  {r:172,en:"My house is far from the station.",ja:"私の家は駅から遠いです。"},
  {r:173,en:"We saw many animals at the zoo.",ja:"私たちは動物園でたくさんの動物を見ました。"},
  {r:174,en:"Please wash your hands before dinner.",ja:"夕食の前に手を洗ってください。"},
  {r:175,en:"Please pick up the garbage on the floor.",ja:"床に落ちているゴミを拾ってください。"},
  {r:176,en:"We had a lot of fun at the party.",ja:"私たちはパーティーでたくさんの楽しみを持ちました（とても楽しみました）。"},
  {r:177,en:"My grandfather lives in Hokkaido.",ja:"私の祖父は北海道に住んでいます。"},
  {r:178,en:"I want to travel around the world.",ja:"私は世界中を旅行したいです。"},
  {r:179,en:"Do you have any other questions?",ja:"ほかの質問はありますか？"},
  {r:180,en:"Please pay attention to the teacher.",ja:"先生に注意を払ってください。"},
  {r:181,en:"Her husband is a doctor.",ja:"彼女の夫は医者です。"},
  {r:182,en:"English is an international language.",ja:"英語は国際的な言語です。"},
  {r:183,en:"This book is very interesting.",ja:"この本はとても面白いです。"},
  {r:184,en:"I often go to the library after school.",ja:"私は放課後によく図書館に行きます。"},
  {r:185,en:"The movie was so boring that I slept.",ja:"その映画はとてもつまらなかったので、私は寝てしまいました。"},
  {r:186,en:"I am glad to meet you.",ja:"あなたにお会いできてうれしいです。"},
  {r:187,en:"Please read the sentences below.",ja:"下記の文を読んでください。"},
  {r:188,en:"Turn right at the next corner.",ja:"次の角を右に曲がってください。"},
  {r:189,en:"This river is very wide.",ja:"この川はとても幅が広いです。"},
  {r:190,en:"The music is too loud.",ja:"音楽が騒がしすぎます（大きすぎます）。"},
  {r:191,en:"The view from the top of the mountain was amazing.",ja:"山の頂上からの景色は驚くべきものでした（素晴らしかったです）。"},
  {r:192,en:"What is the price of this bag?",ja:"このカバンの値段はいくらですか？"},
  {r:193,en:"Each student has a computer.",ja:"各々の生徒がコンピューターを持っています。"},
  {r:194,en:"What are you talking about?",ja:"あなたは何について話しているのですか？"},
  {r:195,en:"The post office is on your right.",ja:"郵便局はあなたの右にあります。"},
  {r:196,en:"It's raining, but let's go out anyway.",ja:"雨が降っていますが、ともかく出かけましょう。"},
  {r:197,en:"Don't worry about me.",ja:"私のことで心配しないでください。"},
  {r:198,en:"She studies English very hard.",ja:"彼女は一生懸命に英語を勉強します。"},
  {r:199,en:"He won an award for his science project.",ja:"彼は理科のプロジェクトで賞をとりました。"},
  {r:200,en:"I want to swim in the ocean.",ja:"私は海で泳ぎたいです。"},
];

async function main() {
  const wb = xlsx.readFile(targetFile);
  const ws = wb.Sheets["3級"];
  const aoa = xlsx.utils.sheet_to_json(ws, { header: 1, defval: "" });

  // Add headers for example columns if missing
  if (!aoa[0][3]) aoa[0][3] = '例文';
  if (!aoa[0][4]) aoa[0][4] = '例文訳';

  let appliedCount = 0;
  for (const item of data) {
    // rank matches the row index (rank 1 = aoa[1])
    const idx = item.r;
    if (aoa[idx] && aoa[idx][3] === "") {
      aoa[idx][3] = item.en;
      aoa[idx][4] = item.ja;
      appliedCount++;
    }
  }

  const newWs = xlsx.utils.aoa_to_sheet(aoa);
  wb.Sheets["3級"] = newWs;
  xlsx.writeFile(wb, outPath);
  console.log(`Successfully applied ${appliedCount} examples to 3級. Saved to ${outPath}`);
}
main().catch(console.error);
