const xlsx = require('xlsx');
const fs = require('fs');
const filePath = String.raw`C:\Users\makoto\Documents\GitHub\VocabularyBase\単語リスト\出題頻度順リストのみ_英検英単語.xlsx`;
const outPath = filePath.replace('.xlsx', '_updated.xlsx');
const targetFile = fs.existsSync(outPath) ? outPath : filePath;

const data = [
  {r:401,en:"I bought several books at the bookstore.",ja:"私は本屋で幾つかの本を買いました。"},
  {r:402,en:"He was tired. However, he kept running.",ja:"彼は疲れていました。しかし、彼は走り続けました。"},
  {r:403,en:"Can you speak any foreign languages?",ja:"あなたは何か外国の言語を話せますか？"},
  {r:404,en:"He has a lot of interest in science.",ja:"彼は科学に多くの興味を持っています。"},
  {r:405,en:"At last, we arrived at the station.",ja:"ついに、私たちは駅に到着しました。"},
  {r:406,en:"Can you speak English?",ja:"あなたは英語を話すことができますか？"},
  {r:407,en:"I dropped my ticket somewhere in the station.",ja:"私は駅のどこかにチケットを落としました。"},
  {r:408,en:"You can use this Wi-Fi for free.",ja:"あなたはこのWi-Fiを無料で使うことができます。"},
  {r:409,en:"It takes less than an hour to go to Tokyo.",ja:"東京に行くのに1時間未満しかかかりません。"},
  {r:410,en:"Your answer to this question is correct.",ja:"この質問へのあなたの答えは正解（正しい）です。"},
  {r:411,en:"Her dog is very clever and can do many tricks.",ja:"彼女の犬はとても利口で、たくさんの芸ができます。"},
  {r:412,en:"This book is very interesting.",ja:"この本は非常に面白いです。"},
  {r:413,en:"It will probably rain tomorrow.",ja:"明日は多分雨が降るでしょう。"},
  {r:414,en:"She held her mother's hand.",ja:"彼女は母親の手を握りました。"},
  {r:415,en:"We must keep our old traditions.",ja:"私たちは古い伝統を守らなければなりません。"},
  {r:416,en:"Do you know the boy over there?",ja:"あそこにいる男の子を知っていますか？"},
  {r:417,en:"What is your favorite color?",ja:"あなたの好きな色は何ですか？"},
  {r:418,en:"Let's play tennis this afternoon.",ja:"今日の午後、テニスをしましょう。"},
  {r:419,en:"The sun is shining brightly today.",ja:"今日は太陽が明るく輝いています。"},
  {r:420,en:"We go to the beach every summer.",ja:"私たちは毎年夏に海へ行きます。"},
  {r:421,en:"These flowers need good soil to grow.",ja:"これらの花が育つには良い土が必要です。"},
  {r:422,en:"He paid three thousand yen for the book.",ja:"彼はその本に3千円支払いました。"},
  {r:423,en:"My grandfather has a beautiful brown horse.",ja:"私の祖父は美しい茶色い馬を飼っています。"},
  {r:424,en:"I lost my umbrella on the train.",ja:"私は電車で傘を失いました（なくしました）。"},
  {r:425,en:"The new school year starts in April in Japan.",ja:"日本では新しい学年は4月に始まります。"},
  {r:426,en:"Our team won the baseball game.",ja:"私たちのチームが野球の試合に勝ちました。"},
  {r:427,en:"Please tell me the true story.",ja:"私に本当の話を伝えて（教えて）ください。"},
  {r:428,en:"A dictionary is a very useful tool.",ja:"辞書はとても役に立つ道具です。"},
  {r:429,en:"Look at that strange cloud in the sky.",ja:"空にあるあの奇妙な雲を見てください。"},
  {r:430,en:"I want to exchange this shirt for a smaller one.",ja:"私はこのシャツをより小さいものと交換したいです。"},
  {r:431,en:"He was shaking with cold.",ja:"彼は寒さで震えていました。"},
  {r:432,en:"Please raise your hand if you know the answer.",ja:"答えがわかっているなら手を挙げてください。"},
  {r:433,en:"I agree with your opinion.",ja:"私はあなたの意見に賛成します。"},
  {r:434,en:"These flowers smell very sweet.",ja:"これらの花はとても甘いにおいがします。"},
  {r:435,en:"Where did you buy that cute bag?",ja:"あなたはどこでそのかわいいカバンを買いましたか？"},
  {r:436,en:"He grew up in a very poor family.",ja:"彼はとても貧乏な家庭で育ちました。"},
  {r:437,en:"My mother gave me a nice present.",ja:"母は私に素敵なプレゼントを与えて（くれて）くれました。"},
  {r:438,en:"Please take an apple from the basket.",ja:"かごからリンゴを一つ取ってください。"},
  {r:439,en:"I take my dog for a walk every morning.",ja:"私は毎朝、犬を散歩に連れて行きます。"},
  {r:440,en:"I have to work hard from Monday to Friday.",ja:"私は月曜日から金曜日まで一生懸命働かなければなりません。"},
  {r:441,en:"We really enjoyed the music concert.",ja:"私たちは音楽コンサートを本当に楽しみました。"},
  {r:442,en:"I studied math very hard last night.",ja:"私は昨夜、数学をとても一生懸命勉強しました。"},
  {r:443,en:"He sold his old car to his friend.",ja:"彼は古い車を友達に売りました。"},
  {r:444,en:"I want to go abroad after graduation.",ja:"私は卒業したら外国に行きたいです。"},
  {r:445,en:"He spoke to me in English.",ja:"彼は私に英語で話しました。"},
  {r:446,en:"My sister made a delicious cake for me.",ja:"私の姉は私のためにおいしいケーキを作ってくれました。"},
  {r:447,en:"He will graduate from university next year.",ja:"彼は来年、大学を卒業します。"},
  {r:448,en:"Please finish the test within an hour.",ja:"テストを1時間以内で終わらせてください。"},
  {r:449,en:"It rained all day yesterday.",ja:"昨日は一日中雨が降りました。"},
  {r:450,en:"I didn't go to school because I was sick.",ja:"私が学校に行かなかったのは、病気だったからです。"},
  {r:451,en:"It is dangerous to swim in this river.",ja:"この川で泳ぐのは危険です。"},
  {r:452,en:"Japan consists of many islands.",ja:"日本はたくさんの島から成り立っています。"},
  {r:453,en:"Kyoto has many beautiful old temples.",ja:"京都には美しい古いお寺がたくさんあります。"},
  {r:454,en:"I missed the beginning of the movie.",ja:"私はその映画の最初を見逃しました。"},
  {r:455,en:"We enjoyed traditional Japanese food at the inn.",ja:"私たちは旅館で伝統的な日本の食べ物を楽しみました。"},
  {r:456,en:"Strawberries are now in season.",ja:"イチゴは今が旬です。"},
  {r:457,en:"Some people believe they will go to heaven.",ja:"天国に行くと信じている人もいます。"},
  {r:458,en:"Don't act like a fool.",ja:"馬鹿のように振る舞ってはいけません。"},
  {r:459,en:"He was injured as a result of the accident.",ja:"彼はその事故の結果、ケガをしました。"},
  {r:460,en:"Please write your name and address here.",ja:"ここにあなたの名前と住所を書いてください。"},
  {r:461,en:"Could you say that again, please?",ja:"もう一度言って（言って）いただけますか？"},
  {r:462,en:"You should not tell a lie.",ja:"嘘をついてはいけません。"},
  {r:463,en:"The city ordered an evacuation before the typhoon hit.",ja:"台風が来る前に、市は避難を指示しました。"},
  {r:464,en:"I found a nice cafe near the station.",ja:"駅の近くで素敵なカフェを見つけました。"},
  {r:465,en:"Can you help me with my homework?",ja:"私の宿題を助けて（手伝って）くれませんか？"},
  {r:466,en:"You should not share personal information online.",ja:"オンラインで個人の情報を共有すべきではありません。"},
  {r:467,en:"You must buy the tickets in advance.",ja:"前もってチケットを買わなければなりません。"},
  {r:468,en:"He decided to drop out of high school.",ja:"彼は高校を中退することを決めました。"},
  {r:469,en:"Many countries got their independence in the 20th century.",ja:"多くの国が20世紀に独立を得ました。"},
  {r:470,en:"My dog is very big, but he is gentle.",ja:"私の犬はとても大きいですが、やさしいです。"},
  {r:471,en:"Could you wait a second, please?",ja:"少しの間、待っていただけますか？"},
  {r:472,en:"Please do not shout in the library.",ja:"図書館の中で叫ばないでください。"},
  {r:473,en:"Today was just an ordinary day.",ja:"今日はただのふつうの一日でした。"},
  {r:474,en:"More and more people are using smartphones.",ja:"ますます多くの人々がスマートフォンを使っています。"},
  {r:475,en:"I have many friends at school.",ja:"私には学校に多くの友達がいます。"},
  {r:476,en:"Please write a sentence in English.",ja:"英語で文を書いてください。"},
  {r:477,en:"Up until yesterday, I didn't know the fact.",ja:"昨日まで、私はその事実を知りませんでした。"},
  {r:478,en:"My brother ate the whole cake by himself.",ja:"私の兄はすべての（丸ごとの）ケーキを一人で食べました。"},
  {r:479,en:"My sister is learning Japanese calligraphy.",ja:"私の姉は日本の書道を習っています。"},
  {r:480,en:"Please stay calm and listen to me.",ja:"落ちついたままで私の話を聞いてください。"},
  {r:481,en:"If you don't study, you will fail the test.",ja:"勉強しなければ、あなたはテストに失敗する（落ちる）でしょう。"},
  {r:482,en:"This box is too heavy for me.",ja:"この箱は私には重すぎます。"},
  {r:483,en:"Thousands of people came to the concert.",ja:"何千もの人々がそのコンサートに来ました。"},
  {r:484,en:"He was so tired that he went to bed early.",ja:"彼はとても疲れていたので早く寝ました。"},
  {r:485,en:"She looked unhappy when she heard the news.",ja:"その知らせを聞いた時、彼女は不幸そう（悲しそう）に見えました。"},
  {r:486,en:"I don't feel well today. I have a cold.",ja:"今日は健康な（良い）気分ではありません。風邪をひいています。"},
  {r:487,en:"We must try to stop violence in schools.",ja:"私たちは学校での暴力を止めるよう努めなければなりません。"},
  {r:488,en:"That new movie was really awesome!",ja:"あの新しい映画は本当にすばらしかったです！"},
  {r:489,en:"The hero fought against a strong enemy.",ja:"そのヒーローは強い敵と戦いました。"},
  {r:490,en:"There is someone standing at the door.",ja:"ドアのところにだれかが立っています。"},
  {r:491,en:"He shot an arrow at the target.",ja:"彼は的に向かって矢を放ちました。"},
  {r:492,en:"I'm sorry to bother you, but can you help me?",ja:"面倒をかけて（邪魔をして）すみませんが、手伝ってくれませんか？"},
  {r:493,en:"My cat and dog sometimes fight.",ja:"私の猫と犬は時々たたかいます（ケンカします）。"},
  {r:494,en:"This book is worth reading twice.",ja:"この本は2回読む価値があります。"},
  {r:495,en:"Bowing is a traditional Japanese custom.",ja:"お辞儀は日本の伝統的な習慣です。"},
  {r:496,en:"I sent an email to my teacher last night.",ja:"私は昨夜、先生にメールを送りました。"},
  {r:497,en:"The teacher will announce the test results tomorrow.",ja:"先生は明日、テストの結果を発表します。"},
  {r:498,en:"It is illegal to park a car here.",ja:"ここに車を駐車するのは違法です。"},
  {r:499,en:"Please turn off all electronic devices during the test.",ja:"テスト中はすべての電子機器の電源を切ってください。"},
  {r:500,en:"Have you seen the latest smartphone?",ja:"あなたは最新のスマートフォンを見ましたか？"},
  {r:501,en:"We have to hurry, or we will miss the train.",ja:"私たちは急がなければなりません、そうしないと電車に乗り遅れます。"},
  {r:502,en:"We stayed at a school shelter during the typhoon.",ja:"私たちは台風の間、学校の避難所に滞在しました。"},
  {r:503,en:"There was a large crowd waiting for the train.",ja:"電車を待っている大きな群衆がいました。"},
  {r:504,en:"Surprisingly, the small boy ate the big pizza all by himself.",ja:"驚いたことには、その小さな男の子は大きなピザを一人で全部食べました。"},
  {r:505,en:"I usually go to school by bus.",ja:"私はたいていバスで学校に行きます。"},
  {r:506,en:"My father gave me a ride to the station.",ja:"父は私を駅まで車に乗せてくれました。"},
  {r:507,en:"My uncle is in the hospital because of cancer.",ja:"私の叔父はがんのために入院しています。"},
  {r:508,en:"The machine checks the temperature every minute.",ja:"その機械は毎分ごとに温度をチェックします。"},
  {r:509,en:"Please fill this glass with water.",ja:"このグラスを水でいっぱいにしてください。"},
  {r:510,en:"It will take ten minutes at most.",ja:"それは多くとも10分しかかからないでしょう。"},
  {r:511,en:"I met my teacher on the way home.",ja:"私は家に帰る道の途中で先生に会いました。"},
  {r:512,en:"Please check the spelling of your name.",ja:"あなたの名前の綴り（スペル）を確認してください。"},
  {r:513,en:"My father often drinks beer on weekends.",ja:"私の父は週末によくビールを飲みます。"},
  {r:514,en:"We need to put some gas in the car.",ja:"私たちは車にガソリンを入れる必要があります。"},
  {r:515,en:"Both of my parents are from Osaka.",ja:"私の両親は二つとも（両方とも）大阪の出身です。"},
  {r:516,en:"Nuclear power can be dangerous.",ja:"核の（原子力の）エネルギーは危険な場合があります。"},
  {r:517,en:"I sat between my mother and father.",ja:"私は母と父の間に座りました。"},
  {r:518,en:"I will try to read this English book.",ja:"私はこの英語の本を読もうとします（挑戦します）。"},
  {r:519,en:"I disagree with you on that point.",ja:"その点について、私はあなたと意見が合いません（反対です）。"},
  {r:520,en:"The strong typhoon destroyed many houses.",ja:"その強い台風は多くの家を破壊しました。"},
  {r:521,en:"Go straight along this street, and you will see the station.",ja:"この通りに沿ってまっすぐ行けば、駅が見えます。"},
  {r:522,en:"Let's eat out tonight.",ja:"今夜は外食しましょう。"},
  {r:523,en:"I would like you to help me with my work.",ja:"私はあなたに私の仕事を手伝ってほしいです。"},
  {r:524,en:"The king lives in a beautiful palace.",ja:"王は美しい宮殿に住んでいます。"},
  {r:525,en:"My mother is baking a cake in the kitchen.",ja:"母はキッチンでケーキを焼いています。"},
  {r:526,en:"He wanted to be a sailor when he was young.",ja:"彼は若い頃、船員になりたいと思っていました。"},
  {r:527,en:"My teacher told me to study harder.",ja:"先生は私にもっと一生懸命勉強するように言いました。"},
  {r:528,en:"The brain is a very important part of the body.",ja:"頭脳（脳）は体の中でとても重要な部分です。"},
  {r:529,en:"Do not use electronic devices during the test.",ja:"テスト中は電子機器を使わないでください。"},
  {r:530,en:"He got fired because he was late for work every day.",ja:"彼は毎日仕事に遅刻したので、解雇されました。"},
  {r:531,en:"Please stand by me.",ja:"私のそばに立っていてください。"},
  {r:532,en:"We crossed the border between France and Italy.",ja:"私たちはフランスとイタリアの国境を越えました。"},
  {r:533,en:"I want to learn about the history of this city.",ja:"この都市の歴史について学びたいです。"},
  {r:534,en:"We need to build a sustainable society.",ja:"私たちは存続可能な（持続可能な）社会を築く必要があります。"},
  {r:535,en:"My friends encouraged me to try again.",ja:"友達が私に再び挑戦するように勇気づけてくれました。"},
  {r:536,en:"He came to school at the usual time.",ja:"彼は通常の時間（いつも通りの時間）に学校に来ました。"},
  {r:537,en:"We use a lot of fossil fuels like oil and coal.",ja:"私たちは石油や石炭のような化石燃料をたくさん使います。"},
  {r:538,en:"The news of his death was a great shock.",ja:"彼の死の知らせは大きなショックでした。"},
  {r:539,en:"Thomas Edison was a famous inventor.",ja:"トーマス・エジソンは有名な発明家でした。"},
  {r:540,en:"I was born in a small village.",ja:"私は小さな村で生まれました。"},
  {r:541,en:"Reading a book before bed is a good habit.",ja:"寝る前に本を読むのは良い習慣です。"},
  {r:542,en:"We must protect the earth for the future.",ja:"私たちは未来のために地球を守らなければなりません。"},
  {r:543,en:"I went to the barber to get my hair cut.",ja:"私は髪を切ってもらうために散髪屋に行きました。"},
  {r:544,en:"In an emergency, please call 119.",ja:"緊急事態の場合は、119番に電話してください。"},
  {r:545,en:"Let's get on the train quickly.",ja:"急いで電車に乗り込みましょう。"},
  {r:546,en:"A strong earthquake hit the town yesterday.",ja:"昨日、強い地震が町を襲いました。"},
  {r:547,en:"Take an umbrella, just in case.",ja:"もしもの場合に備えて、傘を持っていきなさい。"},
  {r:548,en:"The children were laughing in the park.",ja:"子供たちは公園で笑っていました。"},
  {r:549,en:"We went to the zoo for our school field trip.",ja:"私たちは学校の遠足で動物園に行きました。"},
  {r:550,en:"The news spread quickly around the school.",ja:"そのニュースは学校中にすぐに広まりました。"},
  {r:551,en:"I learned a lot from the experience.",ja:"私はその経験から多くを学びました。"},
  {r:552,en:"I like sweet fruits, such as apples and peaches.",ja:"私はリンゴや桃のような、甘い果物が好きです。"},
  {r:553,en:"Let's go to the park.",ja:"公園に行きましょう。"},
  {r:554,en:"It was a tough game, but we won.",ja:"それは困難な（厳しい）試合でしたが、私たちは勝ちました。"},
  {r:555,en:"She bit her lip.",ja:"彼女は唇を噛みました。"},
  {r:556,en:"Hold my hand tightly.",ja:"私の手をしっかりと握って。"},
  {r:557,en:"We walked across the long bridge.",ja:"私たちは長い橋を歩いて渡りました。"},
  {r:558,en:"We had a farewell party for our English teacher.",ja:"私たちは英語の先生のために送別会を開きました。"},
  {r:559,en:"My brother goes to an elementary school.",ja:"私の弟は小学校に通っています。"},
  {r:560,en:"He is the president of the country.",ja:"彼はその国の大統領です。"},
  {r:561,en:"I attended my sister's entrance ceremony.",ja:"私は妹の入学式に出席しました。"},
  {r:562,en:"The test was relatively easy.",ja:"そのテストは比較的簡単でした。"},
  {r:563,en:"Rich people are not always happy.",ja:"お金持ちがいつも幸せとは限りません。"},
  {r:564,en:"We rented a boat and rowed it on the lake.",ja:"私たちはボートを借りて、湖でそれをこぎました。"},
  {r:565,en:"My father drove me to the station.",ja:"父が私を駅まで車で運転して（送って）くれました。"},
  {r:566,en:"The temperature will be low tonight.",ja:"今夜は気温が低くなるでしょう。"},
  {r:567,en:"I am very excited about the school trip.",ja:"私は修学旅行についてとても興奮しています（ワクワクしています）。"},
  {r:568,en:"A bird was singing on the branch of the tree.",ja:"木の実枝の上で鳥が歌っていました。"},
  {r:569,en:"The post office is on your right.",ja:"郵便局はあなたの右側にあります。"},
  {r:570,en:"Do you believe in ghosts?",ja:"幽霊を信じますか？"},
  {r:571,en:"We have a common interest in music.",ja:"私たちは音楽という共通の趣味を持っています。"},
  {r:572,en:"Columbus discovered America.",ja:"コロンブスはアメリカを発見しました。"},
  {r:573,en:"My father wears a tie to work.",ja:"父は仕事にネクタイをしていきます。"},
  {r:574,en:"Coal is a kind of fossil fuel.",ja:"石炭は化石燃料の一種です。"},
  {r:575,en:"I can't study today because I have a headache.",ja:"今日は頭痛がするので勉強できません。"},
  {r:576,en:"My mother cares for my sick grandmother.",ja:"母は病気の祖母の面倒を見ています。"},
  {r:577,en:"He agreed to our new plan.",ja:"彼は私たちの新しい計画を承諾しました。"},
  {r:578,en:"Please feel free to ask me any questions.",ja:"気軽に私に何でも質問してください。"},
  {r:579,en:"A strong wind blew yesterday.",ja:"昨日は強い風が吹きました。"},
  {r:580,en:"In case of fire, use the stairs.",ja:"火事の場合には、階段を使用してください。"},
  {r:581,en:"I will study harder from now on.",ja:"これから（今からは）もっと一生懸命勉強します。"},
  {r:582,en:"That is a very good thought.",ja:"それはとても良い考えです。"},
  {r:583,en:"Your smile makes all the difference.",ja:"あなたの笑顔が大きなちがいを生みます（とても重要です）。"},
  {r:584,en:"We hope for world peace.",ja:"私たちは世界平和を望んでいます。"},
  {r:585,en:"Matsuo Basho is a famous Japanese poet.",ja:"松尾芭蕉は日本の有名な詩人です。"},
  {r:586,en:"He can speak not only English but also French.",ja:"彼は英語だけでなくフランス語もまた話せます。"},
  {r:587,en:"Take an umbrella in case it rains.",ja:"雨が降った場合には備えて傘を持って行きなさい。"},
  {r:588,en:`"Will you come to the party?" "Definitely!"`,ja:"「パーティーに来ますか？」「もちろん！」"},
  {r:589,en:"The sun rose early this morning.",ja:"今朝は太陽が早く昇りました。"},
  {r:590,en:"Please write down your name and address here.",ja:"ここに名前と住所を書き留めて（書いて）ください。"},
  {r:591,en:"This desk is made of wood.",ja:"この机は木で出来ています。"},
  {r:592,en:"I took a domestic flight from Tokyo to Osaka.",ja:"私は東京から大阪まで国内線の飛行機に乗りました。"},
  {r:593,en:"I'd like to stay home rather than go out.",ja:"私は外出するのではなく家にいたいです。"},
  {r:594,en:"Most Japanese students study English.",ja:"たいていの日本の学生は英語を勉強します。"},
  {r:595,en:"Where did you go during summer vacation?",ja:"夏期休暇中にどこに行きましたか？"},
  {r:596,en:"We ran out of milk this morning.",ja:"今朝、牛乳を使い果たして（切らして）しまいました。"},
  {r:597,en:"He spoke loudly to get attention.",ja:"彼は注意を引くために大きな声で話しました。"},
  {r:598,en:"My math teacher is very strict.",ja:"私の数学の先生はとても厳しいです。"},
  {r:599,en:"She has an artistic talent.",ja:"彼女には芸術的な才能があります。"},
  {r:600,en:"In conclusion, we need to try harder.",ja:"結論として、私たちはもっと努力する必要があります。"},
];

async function main() {
  const wb = xlsx.readFile(targetFile);
  const ws = wb.Sheets["3級"];
  const aoa = xlsx.utils.sheet_to_json(ws, { header: 1, defval: "" });
  let c = 0;
  for (const item of data) {
    const idx = item.r;
    if (aoa[idx] && aoa[idx][3] === "") { aoa[idx][3] = item.en; aoa[idx][4] = item.ja; c++; }
  }
  const newWs = xlsx.utils.aoa_to_sheet(aoa);
  wb.Sheets["3級"] = newWs;
  xlsx.writeFile(wb, outPath);
  console.log(`Applied ${c} examples (401-600). Saved.`);
}
main().catch(console.error);
