const xlsx = require('xlsx');
const fs = require('fs');
const filePath = String.raw`C:\Users\makoto\Documents\GitHub\VocabularyBase\単語リスト\出題頻度順リストのみ_英検英単語.xlsx`;
const outPath = filePath.replace('.xlsx', '_updated.xlsx');
const targetFile = fs.existsSync(outPath) ? outPath : filePath;

const data = [
  {r:201,en:"He likes to draw pictures of animals.",ja:"彼は動物の絵を描くのが好きです。"},
  {r:202,en:"Please drink some water.",ja:"少し水を飲んでください。"},
  {r:203,en:"I bought this bread at the new bakery.",ja:"私はこのパンを新しいパン屋で買いました。"},
  {r:204,en:"My father is very busy with his work.",ja:"私の父は仕事でとても忙しいです。"},
  {r:205,en:"What are we having for dinner tonight?",ja:"今夜の夕食は何ですか？"},
  {r:206,en:"It is cold and cloudy today.",ja:"今日は寒くて曇っています。"},
  {r:207,en:"I took the wrong train.",ja:"私は間違った電車に乗ってしまいました。"},
  {r:208,en:"What do you think about this plan?",ja:"この計画についてどう考えますか？"},
  {r:209,en:"English is my favorite subject.",ja:"英語は私のお気に入りの科目です。"},
  {r:210,en:"She wants to become a doctor.",ja:"彼女は医者になりたいと思っています。"},
  {r:211,en:"Please take off your shoes before you enter the room.",ja:"部屋に入る前に靴を脱いでください。"},
  {r:212,en:"Can you imagine life without a smartphone?",ja:"スマートフォンのない生活を想像できますか？"},
  {r:213,en:"Don't go out without an umbrella.",ja:"傘なしに出かけてはいけません。"},
  {r:214,en:"We walked through the dark forest.",ja:"私たちは暗い森を通り抜けました。"},
  {r:215,en:"I have lived here since I was a child.",ja:"私は子供の頃から（以来）ずっとここに住んでいます。"},
  {r:216,en:"The sun is sinking below the horizon.",ja:"太陽が地平線（水平線）の下に沈みかけています。"},
  {r:217,en:"Please turn on the light.",ja:"明かりを点けてください。"},
  {r:218,en:"Don't forget to turn off the TV.",ja:"テレビを消すのを忘れないでください。"},
  {r:219,en:"I want to buy a new bicycle.",ja:"私は新しい自転車を買いたいです。"},
  {r:220,en:"We are going to celebrate my mother's birthday.",ja:"私たちは母の誕生日を祝う予定です。"},
  {r:221,en:"My little sister is afraid of dogs.",ja:"私の妹は犬を恐れています。"},
  {r:222,en:"You must follow the rules of the school.",ja:"学校の規則（ルール）に従わなければなりません。"},
  {r:223,en:"Let's get off the bus at the next stop.",ja:"次の停留所でバスを降りましょう。"},
  {r:224,en:"I dropped my wallet on my way to school.",ja:"学校へ行く途中で財布を落としました。"},
  {r:225,en:"The cat ran away when I approached.",ja:"私が近づくと猫は逃げ去りました。"},
  {r:226,en:"Can you ride a horse?",ja:"あなたは馬に乗れますか？"},
  {r:227,en:"I want to be a teacher in the future.",ja:"私は将来先生になりたいです。"},
  {r:228,en:"Edison was a great scientist.",ja:"エジソンは偉大な科学者でした。"},
  {r:229,en:"I don't like rainy days.",ja:"私は雨降りの日が嫌いです。"},
  {r:230,en:"The sun rises in the east.",ja:"太陽は東から昇ります。"},
  {r:231,en:"Someone stole my bag while I was sleeping.",ja:"私が寝ている間に誰かが私のカバンを盗みました。"},
  {r:232,en:"She looked at herself in the mirror.",ja:"彼女は鏡で自分自身を見ました。"},
  {r:233,en:"I will stay with my aunt next weekend.",ja:"来週末は叔母と一緒に過ごす予定です。"},
  {r:234,en:"Please wait here while I buy the tickets.",ja:"私がチケットを買う間、ここで待っていてください。"},
  {r:235,en:"My uncle works for a big company.",ja:"私の叔父は大きな会社のために働いています。"},
  {r:236,en:"I feel much better today.",ja:"今日はずっと気分が良い（良く感じる）です。"},
  {r:237,en:"He is very quick at solving math problems.",ja:"彼は数学の問題を解くのがとても速いです。"},
  {r:238,en:"Have you ever been to Hawaii?",ja:"今までにハワイに行ったことがありますか？"},
  {r:239,en:"She is good at playing the guitar.",ja:"彼女はギターを弾くのが上手です。"},
  {r:240,en:"I like to read the local newspaper.",ja:"私は地元の新聞を読むのが好きです。"},
  {r:241,en:"Could you lend me your dictionary?",ja:"あなたの辞書を私に貸していただけませんか？"},
  {r:242,en:"We must protect the natural environment.",ja:"私たちは自然環境を守らなければなりません。"},
  {r:243,en:"The dog dug a hole in the garden.",ja:"犬は庭に穴を掘りました。"},
  {r:244,en:"Please explain the rule to me.",ja:"私にそのルールを説明してください。"},
  {r:245,en:"She is wearing a beautiful ring on her finger.",ja:"彼女は指に美しい指輪をしています。"},
  {r:246,en:"I hit my head on the door.",ja:"私はドアに頭をぶつけました。"},
  {r:247,en:"Please wash your hands before eating.",ja:"食べる前に手を洗ってください。"},
  {r:248,en:"What is the shape of this box?",ja:"この箱の形は何ですか？"},
  {r:249,en:"I couldn't think of a good idea.",ja:"私は良いアイデアを思い付くことができませんでした。"},
  {r:250,en:"Japan is a beautiful country.",ja:"日本は美しい国です。"},
  {r:251,en:"My father works for a computer company.",ja:"私の父はコンピューター会社で働いています。"},
  {r:252,en:"This soup has a very good taste.",ja:"このスープはとても良い味がします。"},
  {r:253,en:"I spend a lot of time reading books.",ja:"私は本を読むことに多くの時間を費やします。"},
  {r:254,en:"He looks angry, but in fact, he is very kind.",ja:"彼は怒っているように見えますが、実際にはとても親切です。"},
  {r:255,en:"Kyoto has many foreign visitors every year.",ja:"京都には毎年多くの外国からの観光客が来ます。"},
  {r:256,en:"Please boil some water for the tea.",ja:"お茶のために少しお湯を沸かして（水を煮て）ください。"},
  {r:257,en:"I am interested in Japanese history.",ja:"私は日本の歴史に興味があります。"},
  {r:258,en:"He grew up in a small town.",ja:"彼は小さな町で育ちました。"},
  {r:259,en:"She joined the English club last month.",ja:"彼女は先月、英語クラブに参加しました。"},
  {r:260,en:"I wrote a letter to my grandmother in Hokkaido.",ja:"私は北海道の祖母に手紙を書きました。"},
  {r:261,en:"Why were you late for school today?",ja:"あなたは今日、なぜ学校に遅れたのですか？"},
  {r:262,en:"We don't have school on Saturday.",ja:"私たちは土曜日は学校がありません。"},
  {r:263,en:"Tomorrow is Friday.",ja:"明日は金曜日です。"},
  {r:264,en:"My teacher gave me some good advice.",ja:"私の先生は私にいくつか良い忠告（アドバイス）をくれました。"},
  {r:265,en:"I have a piano lesson on Wednesday.",ja:"私は水曜日にピアノのレッスンがあります。"},
  {r:266,en:"I have a few questions about this book.",ja:"この本についていくつか（少数の）質問があります。"},
  {r:267,en:"Can I have a piece of cake?",ja:"ケーキを一切れもらえますか？"},
  {r:268,en:"I went to the zoo with my family yesterday.",ja:"昨日、家族と一緒に動物園に行きました。"},
  {r:269,en:"I can't understand this math problem.",ja:"私はこの数学の問題を理解できません。"},
  {r:270,en:"Please tell me the reason why you are late.",ja:"あなたが遅れた理由を教えてください。"},
  {r:271,en:"Pick a card from the box.",ja:"箱からカードを一枚選んでください。"},
  {r:272,en:"We live in a peaceful country.",ja:"私たちは平和な国に住んでいます。"},
  {r:273,en:"Can you handle this difficult problem?",ja:"あなたはこの難しい問題を処理できますか？"},
  {r:274,en:"The earth goes round the sun.",ja:"地球は太陽のまわりを回ります。"},
  {r:275,en:"I am very thirsty. May I have some water?",ja:"私はとても喉が渇いています。水をいただけますか？"},
  {r:276,en:"We are in the same class.",ja:"私たちは同じクラスです。"},
  {r:277,en:"My idea is different from yours.",ja:"私の考えはあなたのものとは異なります。"},
  {r:278,en:"Please tell me more about your school.",ja:"あなたの学校についてもっと教えてください。"},
  {r:279,en:"What is the purpose of your trip?",ja:"あなたの旅行の目的は何ですか？"},
  {r:280,en:"Let's play soccer in the park after school.",ja:"放課後、公園でサッカーをしましょう。"},
  {r:281,en:"Wait just a moment, please.",ja:"少しの間待ってください。"},
  {r:282,en:"You should eat a lot of vegetables to be healthy.",ja:"健康になるためにたくさんの野菜を食べるべきです。"},
  {r:283,en:"My birthday is in May.",ja:"私の誕生日は5月です。"},
  {r:284,en:"What is the date today?",ja:"今日の日付は何ですか？"},
  {r:285,en:"It usually snows a lot in February.",ja:"2月は普通、たくさん雪が降ります。"},
  {r:286,en:"I have never seen such a beautiful flower.",ja:"私はそのような美しい花を今まで見たことがありません。"},
  {r:287,en:"Don't talk to him now because he is studying.",ja:"彼は勉強中なので、今は彼に話しかけないでください。"},
  {r:288,en:"His wife is a music teacher.",ja:"彼の妻は音楽の先生です。"},
  {r:289,en:"My family will move to Tokyo next month.",ja:"私の家族は来月東京に引っ越します。"},
  {r:290,en:"His daughter is five years old.",ja:"彼の娘は5歳です。"},
  {r:291,en:"She is always kind to everyone.",ja:"彼女はいつもみんなに親切です。"},
  {r:292,en:"You must be kind to old people.",ja:"お年寄りには親切にしなければなりません。"},
  {r:293,en:"Everyone in my family likes sports.",ja:"私の家族のみんながスポーツを好きです。"},
  {r:294,en:"I agree with your idea.",ja:"私はあなたの考えに賛成です。"},
  {r:295,en:"He fixed the picture to the wall.",ja:"彼は壁に絵を固定しました。"},
  {r:296,en:"Please write your name on this side of the paper.",ja:"紙のこちらの面にあなたの名前を書いてください。"},
  {r:297,en:"I didn't eat breakfast, so I am very hungry now.",ja:"私は朝食を食べなかったので、今とても空腹です。"},
  {r:298,en:"Come here and look at this picture.",ja:"ここに来てこの写真を見てください。"},
  {r:299,en:"I am reading the last page of this book.",ja:"私はこの本の最後のページを読んでいます。"},
  {r:300,en:"I can't study because I have a bad headache.",ja:"ひどい頭痛がするので勉強できません。"},
  {r:301,en:"Mt. Fuji is the highest mountain in Japan.",ja:"富士山は日本で一番高い山です。"},
  {r:302,en:"I can't find my keys anywhere.",ja:"私の鍵がどこにも見つかりません。"},
  {r:303,en:"You should brush your teeth every morning.",ja:"毎朝、歯をみがくべきです。"},
  {r:304,en:"What did you eat for breakfast today?",ja:"今日、朝食に何を食べましたか？"},
  {r:305,en:"Please take off your hat in the room.",ja:"部屋の中では帽子を脱いでください。"},
  {r:306,en:"My father is cooking dinner now.",ja:"私の父は今、夕食を作っています。"},
  {r:307,en:"I usually watch TV after dinner.",ja:"私はたいてい夕食後にテレビを見ます。"},
  {r:308,en:"There are many trees around my house.",ja:"私の家のまわりにはたくさんの木があります。"},
  {r:309,en:"I ate a sandwich and a salad for lunch.",ja:"私は昼食にサンドイッチとサラダを食べました。"},
  {r:310,en:"We had a lot of fun at the school festival.",ja:"私たちは文化祭でとても楽しみました。"},
  {r:311,en:"He likes taking pictures of beautiful nature.",ja:"彼は美しい自然の写真を撮るのが好きです。"},
  {r:312,en:"Who designed this beautiful building?",ja:"誰がこの美しい建物を設計したのですか？"},
  {r:313,en:"Let's share this pizza with everyone.",ja:"みんなでこのピザを分け合いましょう。"},
  {r:314,en:"She has very long black hair.",ja:"彼女はとても長い黒髪をしています。"},
  {r:315,en:"I received an email from my friend in America.",ja:"私はアメリカの友達からメールを受け取りました。"},
  {r:316,en:"He injured his right leg during the soccer game.",ja:"彼はサッカーの試合中に右脚を傷つけました。"},
  {r:317,en:"We went to the theater to see a movie.",ja:"私たちは映画を見るために劇場に行きました。"},
  {r:318,en:"My sister doesn't like watching horror movies.",ja:"私の妹は恐怖映画（ホラー映画）を見るのが好きではありません。"},
  {r:319,en:"I will attend the meeting tomorrow.",ja:"私は明日、会議に出席します。"},
  {r:320,en:"His grandfather died last year.",ja:"彼の祖父は昨年死にました（亡くなりました）。"},
  {r:321,en:"We go to Hawaii every year.",ja:"私たちは毎年ハワイに行きます。"},
  {r:322,en:"He can run very fast.",ja:"彼はとても速く走ることができます。"},
  {r:323,en:"Don't forget to take your umbrella.",ja:"あなたの傘を持って行くのを忘れないでください。"},
  {r:324,en:"It is a pleasure to meet you.",ja:"あなたにお会いできて光栄です（楽しみです）。"},
  {r:325,en:"Please take a picture of us.",ja:"私たちの写真を撮ってください。"},
  {r:326,en:"I can see a small bird in the tree.",ja:"木に小さな鳥が見えます。"},
  {r:327,en:"He is studying art in Paris.",ja:"彼はパリで芸術を勉強しています。"},
  {r:328,en:"I like apples, and I like oranges too.",ja:"私はリンゴが好きで、オレンジもまた好きです。"},
  {r:329,en:"My grandmother lives in Tokyo.",ja:"私の祖母は東京に住んでいます。"},
  {r:330,en:"She wants to be a doctor.",ja:"彼女は医者になりたいと思っています。"},
  {r:331,en:"Mr. Brown teaches us English.",ja:"ブラウン先生は私たちに英語を教えます。"},
  {r:332,en:"I will meet you at the station.",ja:"駅であなたに会います。"},
  {r:333,en:"Let's play tennis after school.",ja:"放課後（学校の後で）、テニスをしましょう。"},
  {r:334,en:"I have never traveled by airplane.",ja:"私は飛行機で旅行したことがありません。"},
  {r:335,en:"I have a good memory of the trip.",ja:"私はその旅行のよい記憶（思い出）があります。"},
  {r:336,en:"I wish you good luck.",ja:"あなたの幸運を望みます（祈ります）。"},
  {r:337,en:"Please answer my question.",ja:"私の質問に答えてください。"},
  {r:338,en:"Can you give me an example?",ja:"私に例をあげてくれますか？"},
  {r:339,en:"We must protect the earth.",ja:"私たちは地球を守らなければなりません。"},
  {r:340,en:"We live in the 21st century.",ja:"私たちは21世紀に生きています。"},
  {r:341,en:"Please wait a moment.",ja:"少しの瞬間（少々）お待ちください。"},
  {r:342,en:"He woke up early as usual.",ja:"彼はいつものように早く起きました。"},
  {r:343,en:"What is the difference between these two?",ja:"これら2つのちがいは何ですか？"},
  {r:344,en:"I have to finish my homework.",ja:"私は宿題を終えなければなりません。"},
  {r:345,en:"Actually, I don't like tomatoes.",ja:"実は、私はトマトが好きではありません。"},
  {r:346,en:"In those days, there were no smartphones.",ja:"当時は、スマートフォンはありませんでした。"},
  {r:347,en:"The children were very noisy in the room.",ja:"子供たちは部屋の中でとても騒がしかったです。"},
  {r:348,en:"My mother works at a hospital.",ja:"私の母は病院で働いています。"},
  {r:349,en:"Have you read any good books recently?",ja:"最近、何か良い本を読みましたか？"},
  {r:350,en:"It is a fact that the earth is round.",ja:"地球が丸いというのは事実です。"},
  {r:351,en:"My grandfather has bad sight.",ja:"私の祖父は視力（見ること）が悪いです。"},
  {r:352,en:"The judge made a fair decision.",ja:"その審判員は公平な決定を下しました。"},
  {r:353,en:"He always complains about the school food.",ja:"彼はいつも学校の給食について不満を言います。"},
  {r:354,en:"The letter will reach him tomorrow.",ja:"その手紙は明日彼に届くでしょう。"},
  {r:355,en:"Did you lose your wallet?",ja:"あなたは財布を失いました（なくしました）か？"},
  {r:356,en:"I have a few questions to ask you.",ja:"あなたにたずねたいいくらかの（いくつかの）質問があります。"},
  {r:357,en:"The baby is playing with a new toy.",ja:"赤ちゃんは新しい玩具（おもちゃ）で遊んでいます。"},
  {r:358,en:"My birthday is in November.",ja:"私の誕生日は11月です。"},
  {r:359,en:"The cat is hiding behind the sofa.",ja:"猫はソファの背後に隠れています。"},
  {r:360,en:"My parents always support me.",ja:"私の両親はいつも私を支援してくれます。"},
  {r:361,en:"It is very cold outside today.",ja:"今日は外側（外）がとても寒いです。"},
  {r:362,en:"What is the matter with you?",ja:"あなたに何の問題（困ったこと）があるのですか？"},
  {r:363,en:"Don't forget to bring your textbook.",ja:"教科書を持ってくるのを忘れないでください。"},
  {r:364,en:"I will wait for you at the station.",ja:"駅であなたを待ちます。"},
  {r:365,en:"My front tooth hurts.",ja:"私の前歯が痛いです。"},
  {r:366,en:"You look tired. You should rest.",ja:"あなたは疲れているように見えます。休息するべきです。"},
  {r:367,en:"Which airline are you flying with?",ja:"どの航空会社で飛行機に乗りますか？"},
  {r:368,en:"I finally finished reading the long book.",ja:"私はついにその長い本を読み終えました。"},
  {r:369,en:"We went fishing in the river yesterday.",ja:"私たちは昨日、川に釣りに行きました。"},
  {r:370,en:"There are many fish in this pond.",ja:"この池にはたくさんの魚がいます。"},
  {r:371,en:"My house is on a small hill.",ja:"私の家は小さな丘の上にあります。"},
  {r:372,en:"The baby started to cry.",ja:"赤ちゃんが泣き始めました。"},
  {r:373,en:"At first, I couldn't speak English well.",ja:"最初は、英語をうまく話せませんでした。"},
  {r:374,en:"I got a good grade on the math test.",ja:"私は数学のテストで良い評価を取りました。"},
  {r:375,en:"The teacher warned us not to go there.",ja:"先生は私たちにそこへ行かないように警告しました。"},
  {r:376,en:"This sofa is very comfortable.",ja:"このソファはとても心地が良いです。"},
  {r:377,en:"I really like the flavor of this tea.",ja:"私はこのお茶の風味がとても好きです。"},
  {r:378,en:"We eat meat and vegetables for dinner.",ja:"私たちは夕食に肉と野菜を食べます。"},
  {r:379,en:"What kind of movies do you like?",ja:"どんな種類の映画が好きですか？"},
  {r:380,en:"The table in the room is square.",ja:"部屋の中にあるテーブルは正方形です。"},
  {r:381,en:"This is a kind of traditional Japanese food.",ja:"これは日本の伝統的な食べ物の一種です。"},
  {r:382,en:"I usually eat bread for breakfast.",ja:"私はたいてい朝食にパンを食べます。"},
  {r:383,en:"He ran quickly to the station.",ja:"彼は駅へ素早く走りました。"},
  {r:384,en:"Please don't burn the paper here.",ja:"ここで紙を燃やさないでください。"},
  {r:385,en:"I was studying in my room at that time.",ja:"あの時は、私は自分の部屋で勉強していました。"},
  {r:386,en:"I don't know the meaning of this word.",ja:"私はこの言葉の意味を知りません。"},
  {r:387,en:"The rain will continue until tomorrow.",ja:"雨は明日まで続くでしょう。"},
  {r:388,en:"He is the manager of this store.",ja:"彼はこのお店の部長（マネージャー）です。"},
  {r:389,en:"I am not tired at all.",ja:"私は全く疲れていません。"},
  {r:390,en:"I want to go abroad next year.",ja:"私は来年外国へ行きたいです。"},
  {r:391,en:"My grandfather was a farmer.",ja:"私の祖父は農家でした。"},
  {r:392,en:"My mother went to the market to buy vegetables.",ja:"母は野菜を買うために市場に行きました。"},
  {r:393,en:"Walking every day is good for your health.",ja:"毎日歩くことはあなたの健康に良いです。"},
  {r:394,en:"These apples are very fresh and delicious.",ja:"これらのリンゴはとても新鮮でおいしいです。"},
  {r:395,en:"They will build a new library here.",ja:"彼らはここに新しい図書館を建てるでしょう。"},
  {r:396,en:"I want to be a doctor in the future.",ja:"私は未来（将来）医者になりたいです。"},
  {r:397,en:"I want to learn about American culture.",ja:"私はアメリカの文化について学びたいです。"},
  {r:398,en:"I have never been to Australia.",ja:"私はオーストラリアに行ったことが１度もありません。"},
  {r:399,en:"The classroom was completely silent.",ja:"教室は完全に静かでした。"},
  {r:400,en:"Don't worry about the test.",ja:"テストについて心配しないでください。"},
];

async function main() {
  const wb = xlsx.readFile(targetFile);
  const ws = wb.Sheets["3級"];
  const aoa = xlsx.utils.sheet_to_json(ws, { header: 1, defval: "" });
  let appliedCount = 0;
  for (const item of data) {
    const idx = item.r;
    if (aoa[idx] && aoa[idx][3] === "") {
      aoa[idx][3] = item.en;
      aoa[idx][4] = item.ja;
      appliedCount++;
    }
  }
  const newWs = xlsx.utils.aoa_to_sheet(aoa);
  wb.Sheets["3級"] = newWs;
  xlsx.writeFile(wb, outPath);
  console.log(`Successfully applied ${appliedCount} examples to 3級. Saved to ${outPath}`);
}
main().catch(console.error);
