const xlsx = require('xlsx');
const fs = require('fs');
const filePath = String.raw`C:\Users\makoto\Documents\GitHub\VocabularyBase\単語リスト\出題頻度順リストのみ_英検英単語.xlsx`;
const outPath = filePath.replace('.xlsx', '_updated.xlsx');
const targetFile = fs.existsSync(outPath) ? outPath : filePath;

const data = [
  {r:801,en:"The waves were very high yesterday.",ja:"昨日は波がとても高かったです。"},
  {r:802,en:"This pen is 100 yen.",ja:"このペンは100円です。"},
  {r:803,en:"We had a debate about the environment.",ja:"私たちは環境についての討論をしました。"},
  {r:804,en:"My mother sang a lullaby to the baby.",ja:"母は赤ちゃんに子守歌を歌いました。"},
  {r:805,en:"This pillow is filled with soft feathers.",ja:"この枕は柔らかい羽で満たされています。"},
  {r:806,en:"We all go through difficult times.",ja:"私たちはみな、困難な時期を通り抜けます（送ります）。"},
  {r:807,en:"He gave me a 1000-yen note.",ja:"彼は私に千円の紙幣（お札）をくれました。"},
  {r:808,en:"I was awake all night.",ja:"私は一晩中目が覚めていました。"},
  {r:809,en:"Leaves fall from the trees in autumn.",ja:"秋には木から葉が落ちます。"},
  {r:810,en:"Are you crazy to go out in this storm?",ja:"この嵐の中を出かけるなんて、あなたは気が狂っていますか？"},
  {r:811,en:"I like sweet fruits, for instance, apples.",ja:"私は甘い果物が好きです、例えばリンゴなど。"},
  {r:812,en:"I don't need a plastic bag, thank you.",ja:"ビニールぶくろは要りません、ありがとう。"},
  {r:813,en:"We had a long discussion about the plan.",ja:"私たちはその計画について長い討論をしました。"},
  {r:814,en:"I am a junior high school student.",ja:"私は中学校の生徒です。"},
  {r:815,en:"Please drop by my house anytime.",ja:"いつでも私の家に立ち寄ってください。"},
  {r:816,en:"This box is made of hard metal.",ja:"この箱は硬い金属でできています。"},
  {r:817,en:"What is his relation to you?",ja:"彼とあなたの関係は何ですか？"},
  {r:818,en:"America was once a British colony.",ja:"アメリカはかつてイギリスの植民地でした。"},
  {r:819,en:"We arrived at the airport two hours early.",ja:"私たちは2時間早く空港に到着しました。"},
  {r:820,en:"In the past, people traveled by horse.",ja:"過去には、人々は馬で旅をしていました。"},
  {r:821,en:"You can always count on me.",ja:"あなたはいつでも私を当てにして（頼りにして）いいですよ。"},
  {r:822,en:"He worked hard to succeed in his business.",ja:"彼はビジネスで成功するために一生懸命働きました。"},
  {r:823,en:"I am certain that he will come.",ja:"彼が来ると私は確信しています（確かです）。"},
  {r:824,en:"I was amazed at the beautiful view.",ja:"私はその美しい景色に驚かされました。"},
  {r:825,en:"Tokyo is a very modern city.",ja:"東京はとても現代的な都市です。"},
  {r:826,en:"I want to get rid of these old clothes.",ja:"私はこれらの古い服を取り除きたい（処分したい）です。"},
  {r:827,en:"The bad weather affected our travel plans.",ja:"悪天候が私たちの旅行計画に影響を与えました。"},
  {r:828,en:"Did you watch the soccer match yesterday?",ja:"昨日、そのサッカーの試合を見ましたか？"},
  {r:829,en:"The station is just beyond that hill.",ja:"駅はあの丘をこえたところにあります。"},
  {r:830,en:"My uncle is the president of this company.",ja:"私の叔父はこの会社の社長です。"},
  {r:831,en:"My sister plays the piano, and she sings as well.",ja:"私の妹はピアノを弾き、同様に歌も歌います。"},
  {r:832,en:"Even a child can answer this question.",ja:"子供でさえこの質問に答えることができます。"},
  {r:833,en:"I am satisfied with the test results.",ja:"私はテストの結果に満足しています。"},
  {r:834,en:"The students listened to the teacher quietly.",ja:"生徒たちは静かに先生の話を聞きました。"},
  {r:835,en:"I like sports, for example, tennis and baseball.",ja:"私はスポーツが好きです、例えばテニスや野球です。"},
  {r:836,en:"Learning a foreign language is fun.",ja:"外国語を学ぶことは楽しいです。"},
  {r:837,en:"He saw some blood on his shirt.",ja:"彼は自分のシャツに少し血がついているのを見ました。"},
  {r:838,en:"I was so tired that I fell asleep quickly.",ja:"私はとても疲れていたので、すぐに眠りに落ちました。"},
  {r:839,en:"You must wait for the traffic signal to turn green.",ja:"交通信号が青に変わるのを待たなければなりません。"},
  {r:840,en:"I decided to go to college.",ja:"私は大学に行くことに決めました。"},
  {r:841,en:"Many people gathered to protest the new law.",ja:"新しい法律に抗議するために多くの人々が集まりました。"},
  {r:842,en:"Many animals are facing extinction.",ja:"多くの動物が絶滅に直面しています。"},
  {r:843,en:"We had a fantastic time at the party.",ja:"私たちはパーティーですばらしい時間を過ごしました。"},
  {r:844,en:"This book belongs to my sister.",ja:"この本は私の妹のものです（妹に属しています）。"},
  {r:845,en:"I am pleased to meet you.",ja:"あなたにお会いできて嬉しい（喜んで）です。"},
  {r:846,en:"Students must wear a uniform at my school.",ja:"私の学校では生徒は制服を着なければなりません。"},
  {r:847,en:"Don't talk to a stranger on the street.",ja:"通りで見知らぬ人（他人）に話しかけてはいけません。"},
  {r:848,en:"Our new neighbor is very kind.",ja:"私たちの新しい隣人はとても親切です。"},
  {r:849,en:"What does this English word mean?",ja:"この英単語は何を意味しますか？"},
  {r:850,en:"It takes courage to speak in front of many people.",ja:"多くの人の前で話すには勇気が必要です。"},
  {r:851,en:"Can I borrow your eraser?",ja:"あなたの消しゴムを借りてもいいですか？"},
  {r:852,en:"It is a quarter to ten.",ja:"10時の4分の1前（9時45分）です。"},
  {r:853,en:"He got out of the car.",ja:"彼は車の外に出ました（車から降りました）。"},
  {r:854,en:"He broke his leg while playing soccer.",ja:"彼はサッカーをしている間に脚を骨折しました。"},
  {r:855,en:"I will try to get up early from now on.",ja:"これからは早く起きるようにします。"},
  {r:856,en:"His brother joined the army.",ja:"彼の兄は陸軍に入隊しました。"},
  {r:857,en:"English is a very important language.",ja:"英語はとても重要な言語です。"},
  {r:858,en:"There are many stars in the universe.",ja:"宇宙にはたくさんの星があります。"},
  {r:859,en:"Please wait here for a while.",ja:"しばらくの間ここで待っていてください。"},
  {r:860,en:"We need to solve this problem together.",ja:"私たちは一緒にこの問題を解決する必要があります。"},
  {r:861,en:"Don't stay up late tonight.",ja:"今夜は遅くまで起きていてはいけません。"},
  {r:862,en:"This medicine is very effective for colds.",ja:"この薬は風邪にとても効果的です。"},
  {r:863,en:"He decided to pursue his dream of becoming a singer.",ja:"彼は歌手になるという夢を追い求めることに決めました。"},
  {r:864,en:"Watch your step when you go down the stairs.",ja:"階段を降りる時は足元に気をつけてください。"},
  {r:865,en:"He reads an average of two books a week.",ja:"彼は週に平均2冊の本を読みます。"},
  {r:866,en:"This topic relates to our history class.",ja:"この話題は私たちの歴史の授業に関係しています。"},
  {r:867,en:"He is a well-known writer in Japan.",ja:"彼は日本で有名な作家です。"},
  {r:868,en:"The car is in a good condition.",ja:"その車は良い状況（状態）です。"},
  {r:869,en:"I don't want to be a burden to my parents.",ja:"私は両親の負担（重荷）になりたくありません。"},
  {r:870,en:"This beautiful table is made of wood.",ja:"この美しいテーブルは木材でできています。"},
  {r:871,en:"Let's rest in the shade of that big tree.",ja:"あの大きな木の陰（日陰）で休みましょう。"},
  {r:872,en:"He was a rich merchant in this town.",ja:"彼はこの町で豊かな商人でした。"},
  {r:873,en:"His son plays baseball very well.",ja:"彼の息子はとても上手に野球をします。"},
  {r:874,en:"I heard a strange noise last night.",ja:"私は昨夜、奇妙な音を聞きました。"},
  {r:875,en:"Please walk on the sidewalk safely.",ja:"安全に歩道を歩いてください。"},
  {r:876,en:"Please be quiet in the library.",ja:"図書館では静かにしてください。"},
  {r:877,en:"There are over seven billion people in the world.",ja:"世界には70億人以上の人々がいます。"},
  {r:878,en:"My family came to my graduation ceremony.",ja:"私の家族が私の卒業式に来ました。"},
  {r:879,en:"By the way, did you finish your homework?",ja:"ところで、宿題は終わりましたか？"},
  {r:880,en:"Cars release carbon dioxide into the air.",ja:"車は空気中に二酸化炭素を放出します。"},
  {r:881,en:"I can't stand the heat of summer.",ja:"私は夏の熱（暑さ）に耐えられません。"},
  {r:882,en:"I get tired easily these days.",ja:"私は最近すぐに疲れます。"},
  {r:883,en:"Perhaps it will rain this afternoon.",ja:"多分今日の午後は雨が降るでしょう。"},
  {r:884,en:"My father works in a car factory.",ja:"私の父は自動車工場で働いています。"},
  {r:885,en:"It's late. Besides, I'm tired.",ja:"遅いです。そのうえ、私は疲れています。"},
  {r:886,en:"She is a very successful writer.",ja:"彼女はとても成功した作家です。"},
  {r:887,en:"We must not use a nuclear weapon.",ja:"私たちは核兵器（核の武器）を使ってはいけません。"},
  {r:888,en:"Please call me back as soon as possible.",ja:"できるだけ早く私に電話をかけ直してください。"},
  {r:889,en:"Look at that cute little dog.",ja:"あのかわいい小さな犬を見てください。"},
  {r:890,en:"Water is necessary for plants.",ja:"水は植物にとって必要です。"},
  {r:891,en:"We should help someone in need.",ja:"私たちは助けが必要な人を助けるべきです。"},
  {r:892,en:"We need to extend the road.",ja:"私たちはその道を広げる必要があります。"},
  {r:893,en:"Money can't buy true happiness.",ja:"お金で真の幸福は買えません。"},
  {r:894,en:"My little sister is scared of spiders.",ja:"私の妹はクモが怖いです。"},
  {r:895,en:"I studied until midnight yesterday.",ja:"私は昨日、真夜中まで勉強しました。"},
  {r:896,en:"Many consumers want to buy cheap goods.",ja:"多くの消費者が安い商品を買いたがっています。"},
  {r:897,en:"What time do you usually get up?",ja:"あなたは普通何時に起きますか？"},
  {r:898,en:"You shouldn't depend on your parents too much.",ja:"両親に頼りすぎてはいけません。"},
  {r:899,en:"You should do it this way.",ja:"あなたはそれをこのようにするべきです。"},
  {r:900,en:"I trust my best friend completely.",ja:"私は親友を完全に信用しています。"},
  {r:901,en:"We watched a funny film on TV.",ja:"私たちはテレビで面白い映画を見ました。"},
  {r:902,en:"To be honest, I don't like tomatoes.",ja:"正直なところ（正直に言うと）、私はトマトが好きではありません。"},
  {r:903,en:"He goes to a college in Tokyo.",ja:"彼は東京の大学に通っています。"},
  {r:904,en:"His death was a great loss to us.",ja:"彼の死は私たちにとって大きな喪失でした。"},
  {r:905,en:"There is a tall tree in front of my house.",ja:"私の家の前に高い木があります。"},
  {r:906,en:"I put some honey in my tea.",ja:"私はお茶に少し蜂蜜を入れました。"},
  {r:907,en:"The dog is running on the green grass.",ja:"犬が緑の草の上を走っています。"},
  {r:908,en:"After a while, he began to speak.",ja:"しばらくして、彼は話し始めました。"},
  {r:909,en:"It suddenly started raining heavily.",ja:"突然、激しく雨が降り始めました。"},
  {r:910,en:"He has a kind heart.",ja:"彼は優しい心を持っています。"},
  {r:911,en:"An earthquake is a natural disaster.",ja:"地震は自然災害です。"},
  {r:912,en:"I'll have tea instead of coffee.",ja:"コーヒーの代わりに紅茶をいただきます。"},
  {r:913,en:"It is too hot to play outside today.",ja:"今日は外で遊ぶには暑すぎます。"},
  {r:914,en:"He is suffering from a serious disease.",ja:"彼は深刻な病気に苦しんでいます。"},
  {r:915,en:"I felt weak after I had a fever.",ja:"熱を出したあと、私は体が弱い（弱っている）と感じました。"},
  {r:916,en:"I saw her pass by my house.",ja:"彼女が私の家を通り過ぎるのを見ました。"},
  {r:917,en:"I could run faster when I was young.",ja:"私は若い頃、もっと速く走ることができた。"},
  {r:918,en:"It takes two hours from Tokyo to Kyoto.",ja:"東京から京都まで2時間かかります。"},
  {r:919,en:"The town is growing rapidly.",ja:"その町は急速に成長しています。"},
  {r:920,en:"I need to charge my smartphone.",ja:"私はスマートフォンを充電する必要があります。"},
  {r:921,en:"I didn't know what the word meant.",ja:"私はその単語が何を意味したのか分かりませんでした。"},
  {r:922,en:"His behavior was very bad today.",ja:"今日の彼のふるまいはとても悪かったです。"},
  {r:923,en:"This chair is hard and uncomfortable.",ja:"この椅子は硬くて心地が悪いです。"},
  {r:924,en:"What is the title of this book?",ja:"この本の題名は何ですか？"},
  {r:925,en:"Water is a very important natural resource.",ja:"水はとても重要な天然資源です。"},
  {r:926,en:"My uncle is a police officer.",ja:"私の叔父は警察官です。"},
  {r:927,en:"He felt ashamed of his mistake.",ja:"彼は自分の間違いを恥じて（恥ずかしく）感じました。"},
  {r:928,en:"Have you eaten lunch yet?",ja:"もう昼食を食べましたか？"},
  {r:929,en:"I sent an image of my dog to my friend.",ja:"私は友達に犬の画像を送りました。"},
  {r:930,en:"Open your mouth, please.",ja:"口を開けてください。"},
  {r:931,en:"I am familiar with this town.",ja:"私はこの町に馴染みがあります（よく知っています）。"},
  {r:932,en:"He seems to be tired today.",ja:"彼は今日、疲れている様に見えます。"},
  {r:933,en:"Hokkaido is in the north of Japan.",ja:"北海道は日本の北にあります。"},
  {r:934,en:"The Earth is a beautiful planet.",ja:"地球は美しい惑星です。"},
  {r:935,en:"I will go, even if it rains.",ja:"たとえ雨だとしても、私は行きます。"},
  {r:936,en:"I asked my teacher about the test.",ja:"私は先生にテストについて聞きました。"},
  {r:937,en:"Fortunately, it was sunny on the day of the picnic.",ja:"幸運にも、ピクニックの日は晴れました。"},
  {r:938,en:"There is no exception to this rule.",ja:"このルールに例外はありません。"},
  {r:939,en:"She bought some beautiful cloth to make a dress.",ja:"彼女はドレスを作るために美しい布（服地）を買いました。"},
  {r:940,en:"I will certainly help you.",ja:"私は確かに（間違いなく）あなたを助けます。"},
  {r:941,en:"Is this to go or for here?",ja:"これはお持ち帰りですか、それともここで食べますか？"},
  {r:942,en:"He will surely win the game.",ja:"彼は確かにその試合に勝つでしょう。"},
  {r:943,en:"I go to school by bus.",ja:"私はバスで学校へ行きます。"},
  {r:944,en:"This device is used to clean the floor.",ja:"この装置は床を掃除するために使われます。"},
  {r:945,en:"My right arm hurts.",ja:"右の腕が痛いです。"},
  {r:946,en:"He is responsible for the project.",ja:"彼はそのプロジェクトに対して責任があります。"},
  {r:947,en:"This watch is my treasure.",ja:"この時計は私の宝物です。"},
  {r:948,en:"I have just finished my homework.",ja:"私はたった今宿題を終えました。"},
  {r:949,en:"I am at the station now.",ja:"私は今、駅に（駅で）います。"},
  {r:950,en:"You can play up to one hour.",ja:"あなたは1時間まで遊ぶことができます。"},
  {r:951,en:"You should sleep at least seven hours.",ja:"あなたは少なくとも7時間は寝るべきです。"},
  {r:952,en:"I will call back later.",ja:"後で折り返し電話します。"},
  {r:953,en:"Dinosaurs died out a long time ago.",ja:"恐竜はずっと昔に絶滅しました。"},
  {r:954,en:"Please sit down on this chair.",ja:"この椅子に座ってください。"},
  {r:955,en:"I have to look after my little brother.",ja:"私は弟の面倒を見なければなりません。"},
  {r:956,en:"Please focus on your study.",ja:"勉強に集中してください。"},
  {r:957,en:"I will show you around the city tomorrow.",ja:"明日、あなたに街を見せて回ります（案内します）。"},
  {r:958,en:"I respect my parents.",ja:"私は両親を尊敬しています。"},
  {r:959,en:"We have to finish this job somehow.",ja:"私たちは何らかの形でこの仕事を終わらせなければなりません。"},
  {r:960,en:"A healthy mind in a healthy body.",ja:"健康な体には健康な精神が宿る。"},
  {r:961,en:"There was a big fire near my house.",ja:"私の家の近くで大きな火事がありました。"},
  {r:962,en:"He will leave for New York tomorrow.",ja:"彼は明日ニューヨークへ出かけます（出発します）。"},
  {r:963,en:"They prayed to god for peace.",ja:"彼らは平和を神に祈りました。"},
  {r:964,en:"He is blind, so he uses a white cane.",ja:"彼は目の見えない人なので、白杖を使います。"},
  {r:965,en:"I am aware of the problem.",ja:"私はその問題に気づいています。"},
  {r:966,en:"I want to take it back.",ja:"私はそれを取り戻したいです。"},
  {r:967,en:"Birds can fly in the sky.",ja:"鳥は空を飛ぶことができます。"},
  {r:968,en:"Tears came from her eyes.",ja:"彼女の目から涙が出ました。"},
  {r:969,en:"He is a new employee at the bank.",ja:"彼は銀行の新しい従業員です。"},
  {r:970,en:"Japanese people like to eat raw fish.",ja:"日本人は生の魚を食べるのが好きです。"},
  {r:971,en:"Water is necessary for our survival.",ja:"水は私たちの存続（生き残ること）に必要です。"},
  {r:972,en:"She realized her dream of becoming a singer.",ja:"彼女は歌手になるという夢を実現しました。"},
  {r:973,en:"Nuclear power is a difficult problem.",ja:"原子力は難しい問題です。"},
  {r:974,en:"Please look both ways before crossing the road.",ja:"道路を渡る前に両方を見てください。"},
  {r:975,en:"This is a new species of butterfly.",ja:"これは蝶の新しい種です。"},
  {r:976,en:"My aunt works as a lawyer in Tokyo.",ja:"私の叔母は東京で弁護士として働いています。"},
  {r:977,en:"There are many cars in the parking lot.",ja:"駐車場にはたくさんの車があります。"},
  {r:978,en:"Please look at the blackboard.",ja:"黒板を見てください。"},
  {r:979,en:"I learned a lot from this book.",ja:"私はこの本からたくさん学びました。"},
  {r:980,en:"The test was pretty difficult.",ja:"そのテストはかなり難しかったです。"},
  {r:981,en:"The school festival was a great success.",ja:"文化祭は大成功でした。"},
  {r:982,en:"The basket is full of apples.",ja:"かごはリンゴでいっぱいです。"},
  {r:983,en:"The boss fired him for being late.",ja:"上司は遅刻したことで彼を首にしました。"},
  {r:984,en:"You must try hard to win the game.",ja:"試合に勝つために一生懸命やらなければなりません。"},
  {r:985,en:"He made dinner by himself.",ja:"彼は自分自身で（一人で）夕食を作りました。"},
  {r:986,en:"I went to bed early because I was sleepy.",ja:"私は眠かったので早く寝ました。"},
  {r:987,en:"It is quite hot today.",ja:"今日はかなり暑いです。"},
  {r:988,en:"The station is three miles away from here.",ja:"駅はここから3マイル離れています。"},
  {r:989,en:"He lies on the sofa to rest.",ja:"彼は休むためにソファに横たわります。"},
  {r:990,en:"We bought apples, oranges, and so on.",ja:"私たちはリンゴやオレンジなどなどを買いました。"},
  {r:991,en:"She is always kind to children.",ja:"彼女はいつも子供に対して親切です。"},
  {r:992,en:"I was scared when I saw the big dog.",ja:"大きな犬を見た時、私はこわがりました。"},
  {r:993,en:"I dislike doing the dishes.",ja:"私はお皿洗いをするのが嫌いです。"},
  {r:994,en:"Go straight ahead for two blocks.",ja:"2ブロック、まっすぐ前方に進んでください。"},
  {r:995,en:"Please excuse me for being late.",ja:"遅れたことをお許しください。"},
  {r:996,en:"Edo is an important period in Japanese history.",ja:"江戸は日本の歴史において重要な時代です。"},
];

async function main() {
  const wb = xlsx.readFile(targetFile);
  const ws = wb.Sheets["3級"];
  const aoa = xlsx.utils.sheet_to_json(ws, { header: 1, defval: "" });
  let c = 0;
  for (const item of data) {
    const idx = item.r;
    if (aoa[idx] && aoa[idx][3] === "") { aoa[idx][3] = item.en; aoa[idx][4] = item.ja; c++; }
  }
  const newWs = xlsx.utils.aoa_to_sheet(aoa);
  wb.Sheets["3級"] = newWs;
  xlsx.writeFile(wb, outPath);
  console.log(`Applied ${c} examples (801-996). Saved.`);
}
main().catch(console.error);
