const xlsx = require('xlsx');
const fs = require('fs');

const filePath = String.raw`C:\Users\makoto\Documents\GitHub\VocabularyBase\単語リスト\出題頻度順リストのみ_英検英単語.xlsx`;
const outPath = filePath.replace('.xlsx', '_updated.xlsx');
const targetFile = fs.existsSync(outPath) ? outPath : filePath;

const generatedData = [
  {"idx": 381, "en": "He decided to study physics at the university.", "ja": "彼は大学で物理学を学ぶことに決めた。"},
  {"idx": 382, "en": "He pulled the trigger of the gun.", "ja": "彼は銃の引き金を引いた。"},
  {"idx": 383, "en": "He has a high social status in the company.", "ja": "彼は会社で高い社会的地位にある。"},
  {"idx": 384, "en": "This museum is definitely worth visiting.", "ja": "この博物館は間違いなく訪れる価値がある。"},
  {"idx": 385, "en": "What is the relation between the two events?", "ja": "その二つの出来事の関係性は何ですか？"},
  {"idx": 386, "en": "I will call you back later.", "ja": "後であなたに電話をかけ直します。"},
  {"idx": 387, "en": "They had a long discussion about political issues.", "ja": "彼らは政治の問題について長い議論をした。"},
  {"idx": 388, "en": "You must tell the truth to your parents.", "ja": "あなたは両親に真実を話さなければならない。"},
  {"idx": 389, "en": "I agree with you partly, but not completely.", "ja": "私はあなたに部分的には同意しますが、完全ではありません。"},
  {"idx": 390, "en": "Scientists observe the stars carefully.", "ja": "科学者たちは注意深く星を観察する。"},
  {"idx": 391, "en": "A small stream runs through the forest.", "ja": "小さな流れが森の中を流れている。"},
  {"idx": 392, "en": "Many people oppose the new law.", "ja": "多くの人々がその新しい法律に反対する。"},
  {"idx": 393, "en": "The weather is quite cold today.", "ja": "今日の天気はかなり寒い。"},
  {"idx": 394, "en": "He became conscious of someone behind him.", "ja": "彼は後ろに誰かいることを意識した。"},
  {"idx": 395, "en": "What do you intend to do this weekend?", "ja": "今週末は何をする意図ですか？"},
  {"idx": 396, "en": "The machine is now in operation.", "ja": "その機械は現在操作中だ。"},
  {"idx": 397, "en": "I recommend you to read this book.", "ja": "この本を読むことをあなたに推薦します。"},
  {"idx": 398, "en": "The main feature of this phone is its camera.", "ja": "この電話の主な特徴はそのカメラだ。"},
  {"idx": 399, "en": "Your suggestion is under consideration.", "ja": "あなたの提案は考慮中だ。"},
  {"idx": 400, "en": "You should eat a healthy diet.", "ja": "あなたは健康的な食事を食べるべきだ。"},
  {"idx": 401, "en": "I closed my eyes in horror at the scene.", "ja": "私はその光景に恐怖して目を閉じた。"},
  {"idx": 402, "en": "The population of Japan is decreasing.", "ja": "日本の人口は減少している。"},
  {"idx": 403, "en": "Bigger is not necessarily better.", "ja": "大きいことが必然的に良いというわけではない。"},
  {"idx": 404, "en": "I completely agree with your opinion.", "ja": "私はあなたの意見に完全に同意する。"},
  {"idx": 405, "en": "I don't know whether he will come or not.", "ja": "彼が来るかどうかどちらかわからない。"},
  {"idx": 406, "en": "He made a careful analysis of the data.", "ja": "彼はデータの注意深い分析を行った。"},
  {"idx": 407, "en": "There is a conflict between the two countries.", "ja": "その二国間には対立がある。"},
  {"idx": 408, "en": "We had extreme weather last summer.", "ja": "昨年の夏は極端な気候だった。"},
  {"idx": 409, "en": "I will follow you wherever you go.", "ja": "あなたがどこに行こうとも私はついて行く。"},
  {"idx": 410, "en": "The internet is a great source of information.", "ja": "インターネットは情報の素晴らしい情報源だ。"},
  {"idx": 411, "en": "Our main objective is to win the game.", "ja": "私たちの主な目標は試合に勝つことだ。"},
  {"idx": 412, "en": "He enjoys the quiet rural life.", "ja": "彼は静かな田舎の生活を楽しんでいる。"},
  {"idx": 413, "en": "Did you read the headline of the newspaper?", "ja": "新聞の見出しを読みましたか？"},
  {"idx": 414, "en": "He works as a financial analyst.", "ja": "彼は金融の分析者として働いている。"},
  {"idx": 415, "en": "You must stop at a red stop sign.", "ja": "赤い一時停止の標識で止まらなければならない。"},
  {"idx": 416, "en": "The police found an important clue to the crime?", "ja": "警察は犯罪への重要な手がかりを見つけた。"},
  {"idx": 417, "en": "The new rule became highly controversial.", "ja": "新しい規則は非常に議論の的になった。"},
  {"idx": 418, "en": "I didn't realize that it was already midnight.", "ja": "すでに深夜だということに私は気がつかなかった。"},
  {"idx": 419, "en": "A beautiful garden surrounds the old house.", "ja": "美しい庭が古い家を取り囲んでいる。"},
  {"idx": 420, "en": "The bank charges a high commission.", "ja": "その銀行は高い手数料を請求する。"},
  {"idx": 421, "en": "Many people seek a better life in the city.", "ja": "多くの人々が都市でのより良い生活を求める。"},
  {"idx": 422, "en": "She is an independent young woman.", "ja": "彼女は独立した若い女性だ。"},
  {"idx": 423, "en": "He proposed a new plan to the team.", "ja": "彼はチームに新しい計画を提案した。"},
  {"idx": 424, "en": "This is an important international conference.", "ja": "これは重要な国際的な会議だ。"},
  {"idx": 425, "en": "I have visited London several times.", "ja": "私はロンドンを幾つか訪れたことがある。"},
  {"idx": 426, "en": "Einstein developed the theory of relativity.", "ja": "アインシュタインは相対性理論を構築した。"},
  {"idx": 427, "en": "She went drinking with her fellow workers.", "ja": "彼女は職場の仲間と飲みに行った。"},
  {"idx": 428, "en": "You should offer your seat to elderly people.", "ja": "年配の人々に席を譲るべきだ。"},
  {"idx": 429, "en": "We need an extension of the deadline.", "ja": "私たちは締め切りの延長が必要だ。"},
  {"idx": 430, "en": "You need proper tools to build a house.", "ja": "家を建てるためには適切な道具が必要だ。"},
  {"idx": 431, "en": "Spices enhance the flavor of food.", "ja": "スパイスは食べ物の風味を際立たせる。"},
  {"idx": 432, "en": "The castle lies just beyond the river.", "ja": "その城は川を越えたところにある。"},
  {"idx": 433, "en": "I hope to hear from you soon.", "ja": "近いうちにあなたから便りがあることを望みます。"},
  {"idx": 434, "en": "The report is due next Friday.", "ja": "レポートは来週の金曜日が期限だ。"},
  {"idx": 435, "en": "We must improve the existing system.", "ja": "私たちは既存のシステムを改善しなければならない。"},
  {"idx": 436, "en": "The company plans to expand its business.", "ja": "その会社はビジネスを拡大する計画だ。"},
  {"idx": 437, "en": "You gave me the wrong answer.", "ja": "あなたは私に間違いの答えを与えた。"},
  {"idx": 438, "en": "He was considered a rebel against the system.", "ja": "彼はシステムに対する反逆者と見なされていた。"},
  {"idx": 439, "en": "Many people suffer from the cold every winter.", "ja": "多くの人々が毎年冬に風邪を患う。"},
  {"idx": 440, "en": "Please reply within a week.", "ja": "一週間以内に返信してください。"},
  {"idx": 441, "en": "This soup has a strange taste.", "ja": "このスープは奇妙な味がする。"},
  {"idx": 442, "en": "He is a strong democrat.", "ja": "彼は強力な民主主義者だ。"},
  {"idx": 443, "en": "Personally, I think it's a bad idea.", "ja": "個人的には、それは悪いアイデアだと思う。"},
  {"idx": 444, "en": "It rained throughout the night.", "ja": "夜を通して終始雨が降っていた。"},
  {"idx": 445, "en": "We must preserve historical buildings.", "ja": "私たちは歴史的建造物を保存しなければならない。"},
  {"idx": 446, "en": "Dogs are highly intelligent animals.", "ja": "犬は非常に知能の高い動物だ。"},
  {"idx": 447, "en": "The child likes to slide down the hill.", "ja": "子どもは丘を滑り降りるのが好きだ。"},
  {"idx": 448, "en": "Baseball is a very popular sport in Japan.", "ja": "野球は日本でとても人気のあるスポーツだ。"},
  {"idx": 449, "en": "He was arrested for the terrible murder.", "ja": "彼はその恐ろしい殺人で逮捕された。"},
  {"idx": 450, "en": "I will attend the meeting tomorrow morning.", "ja": "私は明日の朝の会議に出席するつもりだ。"},
  {"idx": 451, "en": "The world is constantly changing.", "ja": "世界は常に変化している。"},
  {"idx": 452, "en": "The empty boat started to drift on the sea.", "ja": "空のボートが海を漂流し始めた。"},
  {"idx": 453, "en": "What was the result of the exam?", "ja": "試験の結果はどうでしたか？"},
  {"idx": 454, "en": "Safety is our first priority.", "ja": "安全が私たちの第一の優先事項だ。"},
  {"idx": 455, "en": "My knee joint hurts when it rains.", "ja": "雨が降ると膝の関節が痛む。"},
  {"idx": 456, "en": "The program has millions of viewers.", "ja": "その番組は何百万人もの視聴者がいる。"},
  {"idx": 457, "en": "The earth has only one natural satellite.", "ja": "地球には一つだけ自然の衛星がある。"},
  {"idx": 458, "en": "We could hear the sound of distant drums.", "ja": "遠く離れた太鼓の音が聞こえた。"},
  {"idx": 459, "en": "I am waiting for the delivery of my package.", "ja": "私は荷物の配達を待っている。"},
  {"idx": 460, "en": "She was anxious about the test results.", "ja": "彼女はテストの結果を不安に思っていた。"},
  {"idx": 461, "en": "He ran towards the sea enthusiastically.", "ja": "彼は海の方へ熱心に走った。"},
  {"idx": 462, "en": "The company has over 500 employees.", "ja": "その会社には500人以上の従業員がいる。"},
  {"idx": 463, "en": "He played a significant role in the project.", "ja": "彼はそのプロジェクトで重要な役割を果たした。"},
  {"idx": 464, "en": "I have no particular plan for the weekend.", "ja": "週末の特定の予定はありません。"},
  {"idx": 465, "en": "Please pick up the garbage on the floor.", "ja": "床にあるゴミを拾ってください。"},
  {"idx": 466, "en": "He couldn't accept the boss's criticism.", "ja": "彼は上司の批判を受け入れられなかった。"},
  {"idx": 467, "en": "Suddenly, a big bear appeared from the forest.", "ja": "突然、大きなクマが森から現れた。"},
  {"idx": 468, "en": "You need permission to enter this room.", "ja": "この部屋に入るには許可が必要だ。"},
  {"idx": 469, "en": "Wash your hands to prevent a cold virus.", "ja": "風邪のウイルスを防ぐために手を洗いなさい。"},
  {"idx": 470, "en": "He cannot deny the fact that he was there.", "ja": "彼はそこにいたという事実を否定できない。"},
  {"idx": 471, "en": "This watch is very valuable to me.", "ja": "この時計は私にとって非常に価値のあるものだ。"},
  {"idx": 472, "en": "They offered a comprehensive training program.", "ja": "彼らは包括的なトレーニングプログラムを提供した。"},
  {"idx": 473, "en": "I will wait here till he comes back.", "ja": "彼が戻るまで私はここで待ちます。"},
  {"idx": 474, "en": "Make sure to wash your hands properly.", "ja": "適切に手を洗うことを確実にしなさい。"},
  {"idx": 475, "en": "Old people are often vulnerable to cold weather.", "ja": "高齢者はしばしば寒い天候に傷つきやすい。"},
  {"idx": 476, "en": "You should speak to him directly.", "ja": "あなたは彼に直接的に話すべきだ。"},
  {"idx": 477, "en": "The bed occupies most of the room.", "ja": "ベッドが部屋の大部分を占めている。"},
  {"idx": 478, "en": "Children are natively curious about everything.", "ja": "子どもたちは本来あらゆることに好奇心が強い。"},
  {"idx": 479, "en": "Opinions vary from person to person.", "ja": "意見は人によって多様化する。"},
  {"idx": 480, "en": "It is impolite to stare at strangers.", "ja": "知らない人をじっと見つめるのは失礼だ。"},
  {"idx": 481, "en": "He hasn't visited his hometown for a decade.", "ja": "彼はこの10年間、故郷を訪れていない。"},
  {"idx": 482, "en": "The bank was robbed by armed men.", "ja": "銀行は武装した男たちに強盗に入られた。"},
  {"idx": 483, "en": "They seem to be happy with the results.", "ja": "彼らは結果に満足しているように思われる。"},
  {"idx": 484, "en": "We cannot run away from our fate.", "ja": "私たちは自分たちの運命から逃げることはできない。"},
  {"idx": 485, "en": "I tried to convince him to join us.", "ja": "彼が私たちに参加するよう納得させようとした。"},
  {"idx": 486, "en": "Stealing a car is a criminal act.", "ja": "車を盗むことは犯罪の行為だ。"},
  {"idx": 487, "en": "The patient is now in a stable condition.", "ja": "その患者は現在、安定した状態にある。"},
  {"idx": 488, "en": "Babies usually love swimming naked in the bath.", "ja": "赤ちゃんは普通、お風呂で裸で泳ぐのが大好きだ。"},
  {"idx": 489, "en": "They preserve old Jewish traditions.", "ja": "彼らは古いユダヤ人の伝統を保存している。"},
  {"idx": 490, "en": "The bill was finally passed by the senate.", "ja": "その法案はついに上院を通過した。"},
  {"idx": 491, "en": "Where did you hide the money?", "ja": "そのお金をどこに隠しましたか？"},
  {"idx": 492, "en": "He made a quick recovery from the surgery.", "ja": "彼は手術からすぐに回復した。"},
  {"idx": 493, "en": "The mother and child share a special bond.", "ja": "母親と子どもは特別な束縛（絆）を共有している。"},
  {"idx": 494, "en": "That artist painted a portrait of the king.", "ja": "その芸術家は王の肖像画を描いた。"},
  {"idx": 495, "en": "Military intervention may be necessary.", "ja": "軍事的な介在が必要になるかもしれない。"},
  {"idx": 496, "en": "He has shown consistent improvement this year.", "ja": "彼は今年、一貫した改善を見せている。"},
  {"idx": 497, "en": "The investigator searched the area carefully.", "ja": "捜査官はそのエリアを注意深く探した。"},
  {"idx": 498, "en": "I normally wake up at 7 o'clock exactly.", "ja": "私は通常、きっかり7時に起きる。"},
  {"idx": 499, "en": "Let me conclude my speech with a brief summary.", "ja": "簡単な要約で私のスピーチを締めくくらせてください。"},
  {"idx": 500, "en": "He is a well-known writer in this town.", "ja": "彼はこの町でよく知られた作家だ。"},
  {"idx": 501, "en": "Technology development will change our lives.", "ja": "技術の発展が私たちの生活を変えるだろう。"},
  {"idx": 502, "en": "He has a strong desire to win the game.", "ja": "彼はゲームに勝ちたいという強い願望がある。"},
  {"idx": 503, "en": "It will probably rain tomorrow afternoon.", "ja": "明日の午後はおそらく雨が降るだろう。"},
  {"idx": 504, "en": "He didn't respond to my question.", "ja": "彼は私の質問に返答しなかった。"},
  {"idx": 505, "en": "I deny any involvement in the crime.", "ja": "私はその犯罪へのいかなる関与も否定する。"},
  {"idx": 506, "en": "He became the prime minister of the country.", "ja": "彼はその国の大臣（首相）になった。"},
  {"idx": 507, "en": "She sewed a patch on the hole in his jeans.", "ja": "彼女はジーンズの穴に当て布を縫い付けた。"},
  {"idx": 508, "en": "He was elected as the new chairman of the board.", "ja": "彼は委員会の新しい会長に選ばれた。"},
  {"idx": 509, "en": "The city has a rich ethnic diversity.", "ja": "その都市は豊かな民族特有の多様性を持っている。"},
  {"idx": 510, "en": "The cat was sleeping quietly on her lap.", "ja": "猫は彼女のひざの上で静かに眠っていた。"},
  {"idx": 511, "en": "Please refer to the manual for more information.", "ja": "より多くの情報はマニュアルを参照してください。"},
  {"idx": 512, "en": "Can you repair my broken bicycle?", "ja": "壊れた自転車を修理できますか？"},
  {"idx": 513, "en": "What is his current job?", "ja": "彼の現在の仕事は何ですか？"},
  {"idx": 514, "en": "He is obviously tired after a long day.", "ja": "長い一日の後、彼は明らかに疲れている。"},
  {"idx": 515, "en": "There was a beautiful lamp hanging from the ceiling.", "ja": "天井から美しいランプが吊ってあった。"},
  {"idx": 516, "en": "Aristotle was a great Greek philosopher.", "ja": "アリストテレスは偉大なギリシャの哲学者だった。"},
  {"idx": 517, "en": "He committed suicide when he lost his job.", "ja": "彼は仕事を失った時に自殺した。"},
  {"idx": 518, "en": "Humans are naturally social animals.", "ja": "人間は本質的に社会の動物だ。"},
  {"idx": 519, "en": "She has great potential as a young musician.", "ja": "彼女は若い音楽家として素晴らしい潜在的な力を持っている。"},
  {"idx": 520, "en": "The sum of five and three is eight.", "ja": "5と3の合計は8だ。"},
  {"idx": 521, "en": "The horses had to draw a heavy cart.", "ja": "馬たちは重い荷車を引っ張らなければならなかった。"},
  {"idx": 522, "en": "He has rough and hardworking hands.", "ja": "彼はごつごつした働き者の手をしている。"},
  {"idx": 523, "en": "Freedom of speech is a fundamental human right.", "ja": "言論の自由は基本的な人権だ。"},
  {"idx": 524, "en": "He joined the local farmers association.", "ja": "彼は地元の農業連合に参加した。"},
  {"idx": 525, "en": "This farmland yields a good crop of wheat.", "ja": "この農地は豊富な小麦の収穫を産出する。"},
  {"idx": 526, "en": "He wants to be a politician in the future.", "ja": "彼は将来政治家になりたいと考えている。"},
  {"idx": 527, "en": "She works in the sales department of the company.", "ja": "彼女は会社の営業部門で働いている。"},
  {"idx": 528, "en": "He placed the coin in the palm of his hand.", "ja": "彼は手のひらに硬貨を置いた。"},
  {"idx": 529, "en": "A rainbow is a beautiful natural phenomenon.", "ja": "虹は美しい自然の現象だ。"},
  {"idx": 530, "en": "I admit that I made a big mistake.", "ja": "私は大きな間違いをしたことを認める。"},
  {"idx": 531, "en": "He is in a critical condition at the hospital.", "ja": "彼は病院で極めて重要な（危険な）状態にある。"},
  {"idx": 532, "en": "I have a terrible sore throat today.", "ja": "今日はのどがひどく痛い。"},
  {"idx": 533, "en": "You must adapt quickly to the new environment.", "ja": "あなたは新しい環境に素早く適合しなければならない。"},
  {"idx": 534, "en": "His success was largely due to hard work.", "ja": "彼の成功は主として懸命な努力のおかげだった。"},
  {"idx": 535, "en": "This interesting book belongs to me.", "ja": "この面白い本は私に属している。"},
  {"idx": 536, "en": "He failed in his first attempt to climb the mountain.", "ja": "彼は初めて山に登る試みに失敗した。"},
  {"idx": 537, "en": "His deep knowledge impressed me very much.", "ja": "彼の深い知識には私はとても感銘を与えられた。"},
  {"idx": 538, "en": "Please submit your homework by tomorrow.", "ja": "明日までに宿題を提出してください。"},
  {"idx": 539, "en": "I'm bored because there's nothing to do.", "ja": "何もすることがないので私は退屈している。"},
  {"idx": 540, "en": "He bought a new electric car last week.", "ja": "彼は先週新しい電気の車を買った。"},
  {"idx": 541, "en": "We live in a highly civilized modern society.", "ja": "私たちは高度に教養の高い現代社会に生きている。"},
  {"idx": 542, "en": "Many soldiers were killed in combat.", "ja": "多くの兵士が戦闘で殺された。"},
  {"idx": 543, "en": "The storm caused great destruction in the town.", "ja": "その嵐は町に大きな破壊を引き起こした。"},
  {"idx": 544, "en": "The weak country decided to ally itself with America.", "ja": "その弱い国はアメリカと同盟することに決めた。"},
  {"idx": 545, "en": "My sister likes dancing; similarly, I also love it.", "ja": "姉はダンスが好きですが、同様に私も大好きです。"},
  {"idx": 546, "en": "She managed to complete the difficult puzzle.", "ja": "彼女はどうにかその複雑なパズルを完全なものにした。"},
  {"idx": 547, "en": "This machine has a very complicated mechanism.", "ja": "この機械はとても複雑な仕組みをしている。"},
  {"idx": 548, "en": "He went mad when he found out the truth.", "ja": "真実を知ったとき、彼は狂ったようになった。"},
  {"idx": 549, "en": "I absolutely hate people who tell lies.", "ja": "私は嘘をつく人々をひどく嫌う。"},
  {"idx": 550, "en": "Many people are moving from rural areas to urban areas.", "ja": "多くの人々が田舎から都会の地域へ移動している。"},
  {"idx": 551, "en": "That Italian restaurant has a very good reputation.", "ja": "あのイタリアンレストランはとても良い評判がある。"},
  {"idx": 552, "en": "We are now entering a critical new phase of the project.", "ja": "私たちは現在、プロジェクトの極めて重要な新しい段階に入っている。"},
  {"idx": 553, "en": "He studies philosophy at the university.", "ja": "彼は大学で哲学を勉強している。"},
  {"idx": 554, "en": "The tragic shooting incident shocked the entire nation.", "ja": "その悲惨な射撃事件は国中をショックさせた。"},
  {"idx": 555, "en": "Does the total price include tax?", "ja": "合計金額には税金が含まれていますか？"},
  {"idx": 556, "en": "I'd like my delicious steak cooked medium, please.", "ja": "おいしいステーキは中間の焼き加減でお願いします。"},
  {"idx": 557, "en": "She is interested in both classical and contemporary art.", "ja": "彼女は古典芸術と現在の芸術の両方に興味がある。"},
  {"idx": 558, "en": "The jury found the serious suspect guilty of murder.", "ja": "陪審員はその重大な容疑者を有罪と判断した。"},
  {"idx": 559, "en": "They live in a huge house with a beautiful garden.", "ja": "彼らは美しい庭のある巨大な家に住んでいる。"},
  {"idx": 560, "en": "Many beautiful flowers die quickly in winter.", "ja": "多くの美しい花は冬にすぐに死ぬ。"},
  {"idx": 561, "en": "The kind doctor will examine your throat now.", "ja": "優しい医者が今からのどを検査します。"},
  {"idx": 562, "en": "Hard work is an important element of success.", "ja": "懸命な努力は成功の重要な要素だ。"},
  {"idx": 563, "en": "The museum visitors are mainly foreign tourists.", "ja": "博物館の訪問者は主に外国の観光客だ。"},
  {"idx": 564, "en": "Her new beautiful book was a great success.", "ja": "彼女の新しい美しい本は大きな成功を収めた。"},
  {"idx": 565, "en": "Do you believe that green aliens really exist?", "ja": "あなたは緑の宇宙人が本当に存在すると信じますか？"},
  {"idx": 566, "en": "He is a very gentle and kind boy.", "ja": "彼はとても穏やかなで優しい男の子だ。"},
  {"idx": 567, "en": "I only wear a tie on a special occasion.", "ja": "私は特定の祭典の時にだけネクタイを締める。"},
  {"idx": 568, "en": "I will accompany you to the dark station.", "ja": "暗い駅まであなたに同行します。"},
  {"idx": 569, "en": "The old building is virtually empty at night.", "ja": "その古い建物は夜には実質的に空っぽだ。"},
  {"idx": 570, "en": "I need to withdraw some money from the bank.", "ja": "銀行からいくらかのお金を引き出す必要がある。"},
  {"idx": 571, "en": "What do you usually do in your leisure time?", "ja": "余暇の時間は普段何をしていますか？"},
  {"idx": 572, "en": "He is the Japanese representative of our company.", "ja": "彼は私たちの会社の日本の代表者だ。"},
  {"idx": 573, "en": "The dark shape turned out to be a solid mass of rock.", "ja": "その暗い形は固い岩の塊だと判明した。"},
  {"idx": 574, "en": "Please tell me your honest opinion about my work.", "ja": "私の仕事に関するあなたの正直な意見を教えてください。"},
  {"idx": 575, "en": "His silence seems to imply strict agreement.", "ja": "彼の沈黙は厳密な同意をほのめかすように思われる。"},
  {"idx": 576, "en": "Air is a complex mixture of several gases.", "ja": "空気はいくつかの気体の複雑な混合物だ。"},
  {"idx": 577, "en": "Are you fully aware of the serious danger?", "ja": "あなたは深刻な危険に完全に気づいていますか？"},
  {"idx": 578, "en": "A smartphone is a very useful communication device.", "ja": "スマートフォンはとても便利な通信の装置だ。"},
  {"idx": 579, "en": "He was appointed as the deputy strong manager.", "ja": "彼は強力な代理として任命された。"},
  {"idx": 580, "en": "This beautiful flower has a very sweet smell.", "ja": "この美しい花はとても甘いにおいがする。"}
];

async function main() {
  const wb = xlsx.readFile(targetFile);
  const ws = wb.Sheets["準2級"];
  const aoa = xlsx.utils.sheet_to_json(ws, { header: 1, defval: "" });

  if (aoa[0][3] !== '例文') aoa[0][3] = '例文';
  if (aoa[0][4] !== '例文訳') aoa[0][4] = '例文訳';

  let appliedCount = 0;
  for (const item of generatedData) {
    if (aoa[item.idx] && aoa[item.idx][3] === "") {
        aoa[item.idx][3] = item.en;
        aoa[item.idx][4] = item.ja;
        appliedCount++;
    }
  }

  const newWs = xlsx.utils.aoa_to_sheet(aoa);
  wb.Sheets["準2級"] = newWs;
  xlsx.writeFile(wb, outPath);
  console.log(`Successfully applied ${appliedCount} examples. Saved to ${outPath}`);
}

main().catch(console.error);
